### ISSUE TITLE
Reference to Azure App Service Migration Assistant

### ISSUE THREAD

**Issue by fashaikh** [Azure/azure-docs-sdk-dotnet#1035]
https://appmigration.microsoft.com/  is something relevant for this topic and perhaps should be referenced?
Here is a blog post about the tool
https://azure.microsoft.com/en-us/blog/introducing-the-app-service-migration-assistant-for-asp-net-applications/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3372e8a4-e2e4-27a7-a6dd-57935b5aee79
* Version Independent ID: f3a45d80-93cd-ef26-2eb7-f4b9c68dc625
* Content: [Migrate your .NET web app or service to Azure App Service - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-howto-migrate-app-service?view=azure-dotnet)
* Content Source: [docs-ref-conceptual/dotnet-howto-migrate-app-service.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-howto-migrate-app-service.md)
* Service: **app-service**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Closing; the migration tool is now referenced in the See Also section.
