### ISSUE TITLE
I am not sure Microsoft.IdentityModel.JsonWebTokens should be under Client node.

### ISSUE THREAD

**Issue by brentschmaltz** [Azure/azure-docs-sdk-dotnet#1089]
Most of the assemblies that start with Microsoft.IdentityModel are used by servers.
Why are they under Client?

**Comment by jsquire** [comment]
Azure SDK libraries are sorted into two high-level categories:  "management" and "client".    Management libraries are those that work against the ARM plane (aka "mangement plane" or "control plane") and perform resource-centric operations.  All other libraries are considered to be client libraries, as they operate on the data plane.   The categorization isn't intended to reflect the environment in which the library is typically hosted, just to draw the distinction between the management and plane.

I'm going to close this out, as it is quite old at this point and I believe the question was answered.   Please feel free to reopen if you believe that further discussion is needed.
