### ISSUE TITLE
Nav points to Azure Container Service (deprecated)

### ISSUE THREAD

**Issue by noelbundick** [Azure/azure-docs-sdk-dotnet#1115]
"Get started with Kubernetes and Windows containers" points to Azure Container Service, which is deprecated. The link on the page and in the left nav should point to AKS - possibly here: https://docs.microsoft.com/en-us/azure/aks/windows-container-cli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fdab530-6dc9-b2f4-0dde-828a7892e1a4
* Version Independent ID: d62f56ed-3d97-3b67-4c4e-3a0517f770f5
* Content: [Tutorials for .NET and .NET Core apps in Azure - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-tutorials?view=azure-dotnet)
* Content Source: [docs-ref-conceptual/dotnet-tutorials.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-tutorials.md)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Closing, as I'm not seeing the link that was referenced and the only container-related items reference Kubernetes and/or AKS.    

@noelbundick:  Please feel free to reopen if you believe this needs further discussion.
