### ISSUE TITLE
SDK didn't support create NodeJs Azure Function

### ISSUE THREAD

**Issue by wild123** [Azure/azure-docs-sdk-dotnet#1535]
I try to use below azure sdk to create NodeJs Azure Function which Azure client and VS code support but sdk didn't , could you please help check to add one ?

using Microsoft.Azure.Management.ResourceManager.Fluent

like : .WithNetFrameworkVersion(NetFrameworkVersion.V4_6) ?

wiki : https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.appservice.fluent.functionapp.definition.idefinition?view=azure-dotnet

**Comment by AlexGhiondea** [comment]
@wild123 could you share more about what you are trying to achieve? Is this a documentation issue or something else?

**Comment by jsquire** [comment]
Closing this out, as we don't have enough context to assist.   Please feel free to reopen if you believe that further discussion is needed.
