### ISSUE TITLE
Cannot connect to Azure Cosmos Emulator via Gremlin

### ISSUE THREAD

**Issue by TobiasMorell** [Azure/azure-docs-sdk-dotnet#2278]
After upgrading Azure Cosmos Emulator to 2.14.11 I can no longer connect to the emulator Gremlin API using Gremlin.Net v 3.5.2.

## Error message
```
The server returned status code '500' when status code '101' was expected.
```

## Connection code

```cs
var server = new GremlinServer(
    "localhost",
    8901,
    false,
    $"/dbs/{MY_DATABASE}/colls/{MY_COLLECTION}",
    "{MY_KEY}"
);
_client = new GremlinClient(server);
```

## What I've tried

- Upgrading Gremlin.Net to 3.6.1

**Comment by BenjaBobs** [comment]
This is blocking our CI/CD pipeline because the integration tests won't run.

**Comment by jsquire** [comment]
Hi @TobiasMorell.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the documentation for the Azure SDK for .NET packages - we're unable to assist with other Azure issues.  The CosmosDB emulator is not an open-source product and does not have a corresponding GitHub repository for issues.   According to their [troubleshooting documentation](https://learn.microsoft.com/azure/cosmos-db/troubleshoot-local-emulator), it seems that your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
