### ISSUE TITLE
Communication Messages SDK Docs not Situated in Anticipated Directory

### ISSUE THREAD

**Issue by glorialimicrosoft** [Azure/azure-docs-sdk-dotnet#2391]
The Azure.Communication.Messages SDK is currently under the "Communication Messages" directory, but we intended it to be in the "Communication" directory. Would really appreciate your help with correcting this. Thank you!
@danieljurek @archerzz

**Comment by danieljurek** [comment]
@glorialimicrosoft -- This should be fixed and live now. In the future ensure that the `ServiceName` field is correct in the metadata CSV https://eng.ms/docs/products/azure-developer-experience/develop/sdk-docs#ensure-csv-metadata-is-correct
