### ISSUE TITLE
Documentation on OnMessageAsync is insufficient

### ISSUE THREAD

**Issue by sriramva** [Azure/azure-docs-sdk-dotnet#325]
There is a nuance to this method that I did not catch Some remarks should help.

The delegate set with OnMessageAsync needs to be quick at going to a awaited state, or quick to complete. If the method has a of synchronous stuff it does before it goes to a awaited state, the subsequent messages are not picked up from servicebus until the thread really goes to the awaited state. Hence, in the worst case, serializing the handling of the messages to one at a time.

**Comment by CamSoper** [comment]
This is a reference doc issue that requires a change to the underlying `///` comments.

Opened as https://github.com/Azure/azure-service-bus-dotnet/issues/431
