### ISSUE TITLE
Many functions do not include thread safety information.

### ISSUE THREAD

**Issue by leftler** [Azure/azure-docs-sdk-dotnet#364]
Many class definitions do not include thread safety information. For example for https://github.com/Azure/azure-docs-sdk-dotnet/blob/b39513f/xml/Microsoft.Azure.DataLake.Store/AdlsClient.xml does not mention anywhere if the class's methods are safe to use from multiple threads (like WebClient is) or if we need a instance per thread.

**Comment by CamSoper** [comment]
Hi there!  I realize this is an generalized comment, but the change to the specific example requires a change to the underlying `///` comments.

Created new issue https://github.com/Azure/azure-service-bus-dotnet/issues/431

**Comment by CamSoper** [comment]
@leftler FYI, product team has added thread safety information to the next release.
