### ISSUE TITLE
Typo in RequestOptions.OfferType

### ISSUE THREAD

**Issue by MV10** [Azure/azure-docs-sdk-dotnet#392]
Location:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.offertype?view=azure-dotnet#Microsoft_Azure_Documents_Client_RequestOptions_OfferType

The link in Remarks is missing a slash after the .com:
http://azure.microsoft.comdocumentation/articles/documentdb-performance-levels/

**Comment by MV10** [comment]
Also the linked page doesn't actually demonstrate the use of `OfferType`, nor does it enumerate the valid string values we should supply for `OfferType`.

**Comment by CamSoper** [comment]
Sorry for the delay in triaging this.  This is a reference doc issue that requires a change to the underlying `///` comments.  I contacted the owners, and this is a duplicate of an [internal issue](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/117925) (link won't work for non-Microsoft, including here for future reference for myself and other MSFT).

Closing as duplicate for now. Feel free to re-open.

**Comment by rkno82** [comment]
still not fixed :(
