### ISSUE TITLE
RequestOptions.SessionToken has broken formatting

### ISSUE THREAD

**Issue by tonyferrell** [Azure/azure-docs-sdk-dotnet#398]
The documentation page for [RequestOptions.SessionToken](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.sessiontoken?view=azure-dotnet) has broken formatting - several of the paragraphs are rendered in code blocks, and the examples that show up in the github page seem to be missing (or I can't figure out how to get them to show up)

**Comment by CamSoper** [comment]
This is a reference doc issue that requires a change to the underlying `///` comments.

I've created an internal issue for this [here](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/142011) (not accessible outside MSFT, including for reference for me and other MSFT).  Closing this issue for now, feel free to re-open. 🙂 

cc: @mimig1
