### ISSUE TITLE
Getting StoreProcedureName in Pipeline Activity will always show null.

### ISSUE THREAD

**Issue by colitchan** [Azure/azure-docs-sdk-dotnet#450]
I have Azure Data Factory pipeline activity as below JSON, but when using code to get StoreProcedureName, it always return null.

**JSON:**

`{
                "type": "SqlServerStoredProcedure",
                "typeProperties": {
                    "storedProcedureName": "[DataLoad].[uspSwitchPartition]",
                    "storedProcedureParameters": {
                        "tableName": "Core.CustomerDevelopments",
                        "MonthId": "$$Text.Format('{0:yyyyMM}', WindowEnd)"
                    }
                },
                "inputs": [
                    {
                        "name": "ASQL-outCoreCustomerDevelopments-AfterDataLoad"
                    }
                ],
                "outputs": [
                    {
                        "name": "ASQL-outCoreCustomerDevelopments-AfterPartitionSwitch"
                    }
                ],
                "policy": {
                    "timeout": "24.00:00:00",
                    "concurrency": 4,
                    "retry": 3,
                    "longRetry": 3,
                    "longRetryInterval": "01:00:00"
                },
                "scheduler": {
                    "frequency": "Month",
                    "interval": 1
                },
                "name": "SwitchPartition"
            }`

**C# Code in Function APP:**
`                System.Runtime.Serialization.Json.DataContractJsonSerializer serializer = new System.Runtime.Serialization.Json.DataContractJsonSerializer(activity.GetType(),new Type[] { typeof(Microsoft.Azure.Management.DataFactories.Models.SqlServerStoredProcedureActivity) });
                MemoryStream ms = new MemoryStream();
                serializer.WriteObject(ms, activity );
                string json = Encoding.Default.GetString(ms.ToArray());
                log.Info(json);`

**Return:**
`2017-12-27T01:48:09.309 {"TypeProperties":{"__type":"SqlServerStoredProcedureActivity:#Microsoft.Azure.Management.DataFactories.Models","StoredProcedureName":null,"StoredProcedureParameters":null},"Description":null,"Inputs":[{"EndTime":null,"Length":null,"Name":"ASQL-outCoreCustomerDevelopments-AfterDataLoad","StartTime":null}],"LinkedServiceName":null,"Name":"SwitchPartition","Outputs":[{"Name":"ASQL-outCoreCustomerDevelopments-AfterPartitionSwitch"}],"Policy":null,"Scheduler":{"AnchorDateTime":null,"Frequency":"Month","Interval":1,"Offset":null,"Style":null}}`

**Comment by CamSoper** [comment]
Hi there @colitchan !  This doesn't appear to be a documentation issue.  Please open an issue in the azure-sdk-for-net repo [here](https://github.com/Azure/azure-sdk-for-net).

**Comment by ask-imran** [comment]
Hi @CamSoper 

Was there any issue opened for this?
I am running into the same problem now.

**Comment by CamSoper** [comment]
@ask-imran I'm sorry -- I wouldn't know. @shahabhijeet do you happen to know (or know someone on the Data Factory team that can help)?
