### ISSUE TITLE
DocumentClient Class documentation instance lifetime needs clarification

### ISSUE THREAD

**Issue by Gimly** [Azure/azure-docs-sdk-dotnet#482]
Hi,

I feel that the `DocumentClient` [class documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient?view=azure-dotnet) isn't very clear about the lifetime that the `DocumentClient` instance should have.

The first paragraph under the *Remarks* chapter hints to a reuse of the instance for the lifetime of the application, that I would translate by making this instance a Singleton. But the following chapter explains that since it's implementing `IDisposable`, it should be disposed right after it has been used and hints at doing it through a `using`.

The confusion is even aggravated by the fact that I have found two diametrically opposed example. The [CosmosDB tutorial on the web app sample](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-dotnet-application) uses a Singleton, going as far as making all the Repository static. Another example, this time on [MSDN](https://code.msdn.microsoft.com/Implementing-CRUD-61bde6cf) which shows a sample using ASP.Net Core creates the `DocumentClient` instance just for the query, inside of a `using` which means that it's disposed right away.

Also found [this article, again on CosmosDB's documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips) that says that the Cosmos DB client should be a singleton...

So... where's the truth? This looks a lot like the `HttpClient` which, since it implements `IDisposable` everyone was putting in a `using` which is a [bad idea](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).

**Comment by CamSoper** [comment]
Hi there!  Thanks for submitting this.

Since this is a reference doc issue that requires a change to the underlying `///` comments, I've created an [internal issue](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/142023) (visible only to MSFT) to address it.  I'll close this one in the meantime, but feel free to re-open. 🙂 

Thanks!

cc: @mimig1
