### ISSUE TITLE
Isn't the linked nuget package outdated?

### ISSUE THREAD

**Issue by tsahi** [Azure/azure-docs-sdk-dotnet#539]
I believe the recommended package for Service bus is https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/, no? the link at the Client Library section points to https://www.nuget.org/packages/WindowsAzure.ServiceBus.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e82a9b-4ee7-a093-4e13-635551f3c8de
* Version Independent ID: 666177cc-1304-4380-bf6b-6a773810b902
* Content: [Azure Service Bus libraries for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-bus?view=azure-dotnet)
* Content Source: [api/overview/azure/service-bus.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/service-bus.md)
* Service: **service-bus**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
It certainly looks like there's been a new package since we last updated this page!  We'll fix it.  Thanks for pointing it out, @tsahi !

**Comment by CamSoper** [comment]
Fixed in https://github.com/Azure/azure-docs-sdk-dotnet/pull/543
