### ISSUE TITLE
lacking

### ISSUE THREAD

**Issue by gardner711** [Azure/azure-docs-sdk-dotnet#547]
I thought MSFT moved away from that old auto-created documentation style of MSDN that always showed up in the first 10 google results and every developer had to skip past to get to actual examples of working code. This seems like a huge step back. I'm doing the same thing again and skipping these sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61005723-1505-96b1-1597-c47c2f635862
* Version Independent ID: 670cedb3-3642-1d69-d32c-c61f6e18d6b0
* Content: [MessageHandlerOptions Class (Microsoft.Azure.ServiceBus)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.messagehandleroptions?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.ServiceBus/MessageHandlerOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/MessageHandlerOptions.xml)
* Service: **service-bus**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Thanks for the feedback!  I know exactly what you mean.

So we actually have two types of documentation: What we refer to as *conceptual* and *reference*.  Based on your comments, you prefer conceptual docs.  That's fine, I really do, too!  A lot of folks still rely on reference docs to get where they're going, though, and the best way to do reference docs is generating them from the classes themselves.  We've put some [light conceptual content](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-bus?view=azure-dotnet) in the ref libraries to provide an overview, however.

The limitation there is that any additional explanation needs to be provided in `///` comments by the *developers*, not me (the content writer).  I've been pretty successful at getting the devs to update their `///` comments in response to comments here on the docs site, though, so if you have any specifics in mind, please let me know.

If you're looking for comprehensive conceptual docs on Service Bus, [this is a good place to start](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues).

If you have any other comments or questions, feel free to ask me here on GitHub or reach out to me directly via email at Cam.Soper -at- microsoft.com.
