### ISSUE TITLE
Many Methods Only Available in Preview Package

### ISSUE THREAD

**Issue by shgoldbe** [Azure/azure-docs-sdk-dotnet#553]
Several methods in this document are only available in 4.2.x-Preview, but the documentation does not show this at all. The documentation needs to specify the version if it is not the latest stable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a625596f-a5a3-8b17-b9c6-8a91cbfce0d0
* Version Independent ID: 0edea139-8902-e58e-a106-db208ea14cd3
* Content: [TokenProvider Class (Microsoft.ServiceBus)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.tokenprovider?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.ServiceBus/TokenProvider.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus/TokenProvider.xml)
* Service: **service-bus**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Noted! We'll see what we can do here.

**Comment by CamSoper** [comment]
@dend Ideas on how we can deal with the described situation?

**Comment by dend** [comment]
We can document a stable version and a preview version of the Azure SDK "set", if that makes sense. Thoughts?

**Comment by CamSoper** [comment]
@dend Would they be listed twice in the ToC, or would the moniker picker thing come into play?

Let's loop in @sethmanheim !  Hey Seth, opinions?

**Comment by AlexGhiondea** [comment]
Closing this for now. Please re-open if this still needs to be done.
