### ISSUE TITLE
Valid Values for ForceUpdateTag

### ISSUE THREAD

**Issue by timomta** [Azure/azure-docs-sdk-dotnet#563]
The property says it is a string, but it is not clear what the valid values for it are? What do you set it do? How do you use the property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d21c75a-6859-0f6b-d1e6-670474faa61e
* Version Independent ID: cc2bd435-0df1-8fd2-b8d9-3ab31d8ed838
* Content: [VirtualMachineExtension.ForceUpdateTag Property (Microsoft.Azure.Management.Compute.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachineextension.forceupdatetag?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineExtension.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineExtension.xml)
* Service: **big-compute**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-sdk-for-net #4238](https://github.com/Azure/azure-sdk-for-net/issues/4238) via [**ZenHub**](https://www.zenhub.com/)
