### ISSUE TITLE
CloudBlobClient.GetContainerReference doc not useful

### ISSUE THREAD

**Issue by skofman1** [Azure/azure-docs-sdk-dotnet#566]
I'm trying to understand what's the behavior of this method if the container doesn't exist, but it's not readily available in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e14fce0-457a-49b9-5591-53885864e6e9
* Version Independent ID: 6377895a-8fba-2fea-2066-9db4eead9566
* Content: [CloudBlobClient.GetContainerReference(String) Method (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobclient.getcontainerreference?view=azure-dotnet#applies-to)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobClient.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-storage-net #677](https://github.com/Azure/azure-storage-net/issues/677) via [**ZenHub**](https://www.zenhub.com/)
