### ISSUE TITLE
Missing information about Bound/Unbound state of CloudJob

### ISSUE THREAD

**Issue by marcelvb** [Azure/azure-docs-sdk-dotnet#567]
Hi,

I have run into some issues with creating CloudJobs and CloudTasks from C#. I got errors such as:

```
System.InvalidOperationException: The property JobPreparationTask cannot be modified while the object is in the Bound state.
   at Microsoft.Azure.Batch.PropertyAccessor`1.SetValue(T value, Boolean overrideReadOnly, Boolean overrideAccessControl)
```
```
System.InvalidOperationException: The property State cannot be read while the object is in the Unbound state.
   at Microsoft.Azure.Batch.PropertyAccessController.ReadProperty[T](Func`1 propertyReadAction, BindingAccess allowedAccess, String propertyName)
   at Microsoft.Azure.Batch.CloudJob.get_State()
```

```
System.InvalidOperationException: This object is in an invalid state.  Write access is not allowed.
   at Microsoft.Azure.Batch.PropertyAccessor`1.<>c__DisplayClass19_0.<SetValue>b__0()
   at Microsoft.Azure.Batch.PropertyAccessor`1.SetValue(T value, Boolean overrideReadOnly, Boolean overrideAccessControl)
```

I'm confused when and when not I can read/write properties in relation to calls to:

- `JobOperations.ListJobs()`
- `JobOperations.GetJob()`
- `JobOperations.CreateJob()`
- `Cloud.Job.Commit()`
- `Cloud.Job.CommitChanges()`
- `Cloud.Job.Refresh()`

The errors thrown are not very helpful, nor is the documentation. Could you please clarify this subject a bit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba097f44-6bcc-cb5a-208d-47db4415053e
* Version Independent ID: bafba85f-c12a-3396-aeee-71a3d08b8909
* Content: [CloudJob Class (Microsoft.Azure.Batch)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.cloudjob?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Batch/CloudJob.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Batch/CloudJob.xml)
* Service: **batch**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-sdk-for-net #4237](https://github.com/Azure/azure-sdk-for-net/issues/4237) via [**ZenHub**](https://www.zenhub.com/)
