### ISSUE TITLE
ProvisioningState  Documentation Needs Improvement

### ISSUE THREAD

**Issue by thepenguinmaster** [Azure/azure-docs-sdk-dotnet#568]
Because provisioning state is a string which is ambiguous, it would be important to list the possible values, or provide an enumeration for this field. At the very least, possible values for deployment states should be listed. 
"Provisioning State (Get) - Gets the state of provisioning" is not proper documentation IMO. Typically when writing documentation it is bad practice to simply add spaces to the name of the item being described with small changes in word order. Some elaboration here would be beneficial. I assume this documentation is auto generated and simply needs to be filled in. 

**Reasoning**: 
There are many times when in an application you may want to make decisions based on the state of a deployment. Having a list of know values would be helpful for this, since it is difficult/impossible to know what will come from Azure in this case. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cd038f-7db0-6ab1-bc3a-b4d509f35947
* Version Independent ID: 39120ec7-7010-6a56-c17c-a9e00d598fd0
* Content: [DeploymentPropertiesExtended.ProvisioningState Property (Microsoft.Azure.Management.ResourceManager.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.models.deploymentpropertiesextended.provisioningstate?view=azure-dotnet#Microsoft_Azure_Management_ResourceManager_Models_DeploymentPropertiesExtended_ProvisioningState)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Models/DeploymentPropertiesExtended.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Models/DeploymentPropertiesExtended.xml)
* Service: **azure-resource-manager**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-sdk-for-net #4236](https://github.com/Azure/azure-sdk-for-net/issues/4236) via [**ZenHub**](https://www.zenhub.com/)
