### ISSUE TITLE
Include TryReceive and TryReceiveAsync methods in IMessageReceiver

### ISSUE THREAD

**Issue by nisubr** [Azure/azure-docs-sdk-dotnet#571]
Please provide the following methods in IMessageReceiver:
```
bool TryReceive(out Message msg, TimeSpan timeout)
Task<bool> TryReceiveAsync(out Message msg, TimeSpan timeout)
```
So that we can use these like:
```
if (TryReceive(out Message msg, TimeSpan.FromSeconds(30))
{
    ...
}
else
{
    ...
}
```

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-service-bus-dotnet #443](https://github.com/Azure/azure-service-bus-dotnet/issues/443) via [**ZenHub**](https://www.zenhub.com/)
