### ISSUE TITLE
Application insights docs non-informative, contains errors.

### ISSUE THREAD

**Issue by las3r** [Azure/azure-docs-sdk-dotnet#572]
The biggest constructor is mentioned with having two 'dependencyName', which isn't correct. Also it would be very helpful to know how 'data', 'target' and 'DependancyTypeName' will show up in our AI dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2d6c30-d2f6-5b80-7820-aff2ee35aada
* Version Independent ID: 962248d9-c25b-bc7e-b9ee-55ab26af5daa
* Content: [DependencyTelemetry Constructor (Microsoft.ApplicationInsights.DataContracts)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.dependencytelemetry.-ctor?view=azure-dotnet#Microsoft_ApplicationInsights_DataContracts_DependencyTelemetry__ctor_System_String_System_String_System_String_System_String_System_DateTimeOffset_System_TimeSpan_System_String_System_Boolean_)
* Content Source: [xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml)
* Service: **application-insights**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
This issue was moved to Microsoft/ApplicationInsights-dotnet#778

**Comment by SergeyKanzhelev** [comment]
This link explains semantics of every field: https://docs.microsoft.com/en-us/azure/application-insights/application-insights-data-model-dependency-telemetry

You can see all the fields in raw format in [analytics](https://analytics.applicationinsights.io/Demo?q=H4sIAAAAAAAAA0tJLUjNS0nNS85MLVaoUSgoys9KTS5RKKksSNVRyEvMBZIpiSWJADKWTSQnAAAA&timespan=P1D) using [query](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net-dependencies#analytics) like this: dependencies | project type, name, data

In UI you can click on "..." or "show more" (depending on the whether you enabled distributed tracing  view). It will show you all properties.

**Comment by SergeyKanzhelev** [comment]
Issue with the wrong name is a generator issue, not a product problem. Reopening issue for tracking it

**Comment by SergeyKanzhelev** [comment]
Oopps... I cannot re-open. @CamSoper please reopen to track it
