### ISSUE TITLE
Does not document exceptions thrown

### ISSUE THREAD

**Issue by paulhickman-a365** [Azure/azure-docs-sdk-dotnet#573]
Can you add documentation on the exceptions thrown by extension methods. This is present for the normal methods of the KeyVaultClient but not the extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac49d6d8-a550-3da9-0cdb-a70aea52eb3a
* Version Independent ID: 6cab7777-3293-3262-b87d-3dcde5e0e528
* Content: [KeyVaultClientExtensions.GetSecretAsync Method (Microsoft.Azure.KeyVault)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.getsecretasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml)
* Service: **key-vault**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-sdk-for-net #4235](https://github.com/Azure/azure-sdk-for-net/issues/4235) via [**ZenHub**](https://www.zenhub.com/)
