### ISSUE TITLE
Incorrect / misleading information on this page on Disposing of the DocumentClient

### ISSUE THREAD

**Issue by ciarancolgan** [Azure/azure-docs-sdk-dotnet#577]
Hi - the 'code' text in the 'Remarks' section on this page which begins: "When your app uses DocumentClient, you should call its IDisposable.Dispose implementation when you are finished using it...." - this is incorrect / misleading information. This is actually contradicted by the (correct) information directly above it in the 'Remarks' section - that users should be creating a DocumentClient and caching it for future use as it is threadsafe. To have the correct information followed by an incorrect code sample is very confusing - can you update the sample to show a static DocumentClient being created, with the 'using' approach as an alternative fallback? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76704596-4890-d949-e4bb-e98345cb3258
* Version Independent ID: fe52c0b4-01af-f215-45f0-74940289becf
* Content: [DocumentClient Class (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Documents.Client/DocumentClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Hi there! Thanks for submitting this.

Since this is a reference doc issue that requires a change to the underlying /// comments, I've created an [internal issue](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/232537) (visible only to MSFT) to address it. I'll close this one in the meantime, but feel free to re-open. 🙂

Thanks!

cc: @mimig1
