### ISSUE TITLE
Client library issue

### ISSUE THREAD

**Issue by Basek** [Azure/azure-docs-sdk-dotnet#591]
It is very cool but Microsoft.PowerBI.Api still don't support Net Standard. And I think it should be mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f23ae7f-4493-e285-c093-6fa10e20cbcc
* Version Independent ID: f3a805d2-5c34-ab67-41a8-a8880917dae2
* Content: [Power BI Embedded libraries for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/powerbi-embedded?view=azure-dotnet)
* Content Source: [api/overview/azure/powerbi-embedded.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/powerbi-embedded.md)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by AlexGhiondea** [comment]
The `Microsoft.PowerBI.Api` library now supports .NET Standard 2.0
