### ISSUE TITLE
Technical note

### ISSUE THREAD

**Issue by MahdiZare** [Azure/azure-docs-sdk-dotnet#592]
hello,
after 
 while(results.Read())
    {
        Console.WriteLine("Column 0: {0} Column 1: {1}", results[0], results[1]);
    }
You must close the connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2ee884-131a-5641-b433-3a305239f3a4
* Version Independent ID: 90f66938-afd9-1ffe-69ab-9ccf244e2956
* Content: [Azure SQL Database APIs for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/sql?view=azure-dotnet)
* Content Source: [api/overview/azure/sql.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/sql.md)
* Service: **sql-database**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
We're using a `using` block to dispose of the connection object when we're done, which also closes the connection. [More info}(https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection?view=netframework-4.7.2).
