### ISSUE TITLE
What are the possible values?

### ISSUE THREAD

**Issue by amp64** [Azure/azure-docs-sdk-dotnet#593]
How does one interpret the value here? Is zero success? One? Its an Int64 so there is a huge range of values, but what do any of them mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b630f572-f1b5-555f-0479-49dd81e2aac1
* Version Independent ID: 68a87428-e08b-4c5b-dc66-2c28d1a8f7ac
* Content: [NotificationOutcome.Success Property (Microsoft.Azure.NotificationHubs)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.notificationoutcome.success?view=azure-dotnet#Microsoft_Azure_NotificationHubs_NotificationOutcome_Success)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/NotificationOutcome.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/NotificationOutcome.xml)
* Service: **notification-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
I'm sorry this issue flew under the radar. Were you ever able to get the answer you needed, or would you like me to try to track it down?
