### ISSUE TITLE
Is this class thread safe?

### ISSUE THREAD

**Issue by justinoverton** [Azure/azure-docs-sdk-dotnet#597]
On the old documentation site classes had a section about thread safety. This site does not seem to have the standard section. That aside, is this thread safe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab744f5-b43b-6c71-bc5a-c524c3cf473a
* Version Independent ID: e96e8519-ec49-7383-c31f-510f20966cc9
* Content: [ServicePartitionClient<TCommunicationClient> Class (Microsoft.ServiceFabric.Services.Communication.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.communication.client.servicepartitionclient-1?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceFabric.Services.Communication.Client/ServicePartitionClient`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceFabric.Services.Communication.Client/ServicePartitionClient`1.xml)
* Service: **service-fabric**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@rwike77 Do you know if this class is thread-safe?

**Comment by rwike77** [comment]
@oanapl  can you answer this one (or find someone who can)?  Thanks

**Comment by oanapl** [comment]
@BharatNarasimman

**Comment by BharatNarasimman** [comment]
Yes ServicePartitionClient is threadsafe
