### ISSUE TITLE
Maximum number of user objects in a database?

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-docs-sdk-dotnet#600]
Documentation states: "You have reached your quota of user objects for this database"
WHAT is the quota value?  10, 100, 1000?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35d4a-7024-5b1b-27d8-0ca203824e01
* Version Independent ID: 767887a2-ab6f-8e67-a668-3a6e5793d4a7
* Content: [DocumentClient.CreateUserAsync Method (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.createuserasync?redirectedfrom=MSDN&view=azure-dotnet#overloads)
* Content Source: [xml/Microsoft.Azure.Documents.Client/DocumentClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@mimig1 Do you know the answer to this?

**Comment by bdcoder2** [comment]
No clue -- only the keepers of the code, who neglected to include those magic numbers in the documentation would know !

**Comment by CamSoper** [comment]
Oh sorry, didn't mean to ping you. I was looping in @mimig1, who's the docs expert for Cosmos DB. 🙂

**Comment by aliuy** [comment]
It's configurable; we can increase the quota here - can we start an e-mail thread on this? We'll need the number of desired user objects and the cosmos db endpoint to be configured (e.g. xxxx.documents.azure.com). Can you start an e-mail thread with us? (andrl at microsoft dotcom)

**Comment by CamSoper** [comment]
@bdcoder2 Please copy me as well - Cam.Soper at microsoft dotcom.

I'm going to close this issue for now. Let me know if you'd like me to reopen it!

Thanks, @mimig1 and @aliuy!
