### ISSUE TITLE
The latest api-version 2018-03-31 is not returning UsageDetail.BillableQuantity property value

### ISSUE THREAD

**Issue by divyeshgohil85** [Azure/azure-docs-sdk-dotnet#602]
can you please confirm the latest api-version 2018-03-31 returns the value in the UsageDetail.BillableQuantity property for https://management.azure.com//subscriptions/{subscriptionid}/providers/Microsoft.Consumption/usageDetails endpoint output JSON?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627a6752-29d1-2522-540e-2d4ee4f7186e
* Version Independent ID: c0e004c4-8e8e-19f6-cf7c-ad66c6cac0c2
* Content: [UsageDetail.BillableQuantity Property (Microsoft.Azure.Management.Consumption.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.consumption.models.usagedetail.billablequantity?view=azure-dotnet#Microsoft_Azure_Management_Consumption_Models_UsageDetail_BillableQuantity)
* Content Source: [xml/Microsoft.Azure.Management.Consumption.Models/UsageDetail.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Consumption.Models/UsageDetail.xml)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by dankim25** [comment]
Any updates on this? Also not seeing BillableQuantity not returning a value..

**Comment by CamSoper** [comment]
Sorry, had a death in the family and it threw off my groove.

@dsgouda Do you know who might be able to answer this?

**Comment by dsgouda** [comment]
Sorry to hear that. Could you start an email thread with @salameer / @sphibbs  who have more context here?

**Comment by salameer** [comment]
@asarkar84 and @parisa-naeimi 

Kindly help with Cam's Question if possible

**Comment by dankim25** [comment]
Sorry for your lost. 

So been doing more digging, and it seems like Consumption API does not return fields related to cost (pretaxCost, billableQuantity, etc). I see now that the Billing API, on the other hand, does return cost data. 

Have those fields just been deprecated from Consumption or is this an error?

**Comment by divyeshgohil85** [comment]
@dankim25 which billing API endpoint returns these(pretaxCost, billableQuantity) data?

**Comment by dankim25** [comment]
https://docs.microsoft.com/en-us/rest/api/billing/enterprise/billing-enterprise-api-usage-detail I was using this one. Does seem to be a enterprise specific api however..

**Comment by CamSoper** [comment]
@dankim25 @divyeshgohil85 It's been a while with no additional discussion on this. Are we okay to close it?
