### ISSUE TITLE
What is the difference between Update and Replace?

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-docs-sdk-dotnet#606]
The [REST API doc](https://docs.microsoft.com/en-us/rest/api/cosmos-db/triggers) doesn't mention Update at all. What's the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa6034a3-9dea-abf8-0421-5aadc8d0f6d4
* Version Independent ID: 4a1855e4-2297-186d-5d9f-be46e4125f8d
* Content: [TriggerOperation Enum (Microsoft.Azure.Documents)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.triggeroperation?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents/TriggerOperation.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents/TriggerOperation.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@mimig1 Can you please help answer this?

**Comment by CamSoper** [comment]
@SnehaGunda This is an older issue but I want to make sure we post an answer here before I close it. Are you able to help me out, please? 🙂

**Comment by SnehaGunda** [comment]
@thomaslevesque and @CamSoper I dropped a note to the SDK team to update doc
