### ISSUE TITLE
Please explain Primary Key vs Primary Password

### ISSUE THREAD

**Issue by largeDachshund** [Azure/azure-docs-sdk-dotnet#610]
Breaking changes abound.  how about a clarification of these terms.  If you don't get this right, nobody is connecting to cosmosdb.  kinda urgent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56afaf46-f632-537d-9295-2bb62e179fa2
* Version Independent ID: cf9f3c17-b3aa-0da9-fcd9-7248d09116f6
* Content: [DocumentClient.AuthKey Property (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.authkey?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents.Client/DocumentClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@largeDachshund It's true, sometimes there are lots of breaking changes and getting things clarified is important.  Cosmos isn't a technology I've focused a lot on personally, can you please clarify your question a bit? Where is the confusion coming from?

cc: @mimig1

**Comment by CamSoper** [comment]
Closing this as stale. @largeDachshund please feel free to reopen with additional info!  Thank you for reporting it.

cc: @SnehaGunda
