### ISSUE TITLE
Certain generated XML formatting gets rendered incorrectly in docs

### ISSUE THREAD

**Issue by zikunfan** [Azure/azure-docs-sdk-dotnet#615]
error on api description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1385cc44-bcdf-97e1-14f8-05dae39c3e5b
* Version Independent ID: 84f32302-2baa-bc4b-c210-cd777c22b428
* Content: [Microsoft.Azure.EventHubs.Processor Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Azure.EventHubs.Processor.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.EventHubs.Processor.xml)
* Service: **event-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Yep. The problem is I don't know if whatever parser renders the XML is handling something wrong, or if the developers are misformatting their `///` comments. Thought I'd ask if you knew before I escalate to the devs. 🙂

**Comment by CamSoper** [comment]
Opened [Live Site Incident](https://icm.ad.msft.net/imp/v3/incidents/details/75510350/home). Attn: @dend

**Comment by dend** [comment]
We are following-up here - @TianqiZhang has a fix that will be deployed soon, that will mitigate the problem.

**Comment by CamSoper** [comment]
Hey @dend and @TianqiZhang - Is this fix still on-deck?

**Comment by spelluru** [comment]
Seems to be fixed now. #please-close

**Comment by spelluru** [comment]
Hi @dend @CamSoper - is the issue fixed now? Could you please close the issue if it's already fixed? Thanks.

**Comment by CamSoper** [comment]
@spelluru seems to be.
