### ISSUE TITLE
Samples needed

### ISSUE THREAD

**Issue by msfcolombo** [Azure/azure-docs-sdk-dotnet#620]
Please add sample return values, such as ones for actual storage and emulated storage. We need to know if the URI contains port, path, the scheme, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b738f796-dd8f-bbca-35f2-f4418a1aa2f7
* Version Independent ID: 4f38ed94-a79a-2869-2b80-cb229b710564
* Content: [CloudBlobClient.BaseUri Property (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobclient.baseuri?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobClient.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by AlexGhiondea** [comment]
@msfcolombo please take a look at our new set of libraries [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage). Please open a new issue in that repo if there are samples you would like to see that are not there.
