### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by OwenTN** [Azure/azure-docs-sdk-dotnet#623]
Links to the Microsoft.ServiceFabric.Data.Collections namespace documentation are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4558a5d-f020-617b-0d48-6d5d3a1694a1
* Version Independent ID: bcaa5b89-fdbb-ddf2-ad4c-965f0aebfd29
* Content: [Microsoft.ServiceFabric.Data Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.ServiceFabric.Data.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.ServiceFabric.Data.xml)
* Service: **service-fabric**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@dend Looks like we're maybe missing a namespace? Can you take a look?

**Comment by CamSoper** [comment]
Seems to be fixed without changes. CI hiccup?
