### ISSUE TITLE
Set value

### ISSUE THREAD

**Issue by jodecler** [Azure/azure-docs-sdk-dotnet#626]
Why is the expiration time always 9999/12/31? 
Why can't I change the expiration time?
How can i change the expiration time?

I want to change this from the default time because our business flow requires this to enforce security reasons. 

This documentation says I can get or set the expiration time, I've made a pull request to change this documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc65fedd-1700-0ab5-08ad-1e0a83ecf0ad
* Version Independent ID: 450edc30-be48-1807-8359-27ca44689fc5
* Content: [RegistrationDescription.ExpirationTime Property (Microsoft.Azure.NotificationHubs)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.registrationdescription.expirationtime?view=azure-dotnet#Microsoft_Azure_NotificationHubs_RegistrationDescription_ExpirationTime)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/RegistrationDescription.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/RegistrationDescription.xml)
* Service: **notification-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@dimazaid @spelluru @ggailey777 Do any of you know the answer to this question?

**Comment by CamSoper** [comment]
@dimazaid @spelluru @ggailey777 I've let this one sit a little too long. Do you guys know who I could ask?

@jodecler I imagine your need for this answer has probably long passed, and I'm sorry. I'll do my best to track down an answer for you.

**Comment by DriesPeeters** [comment]
Dear,

This is still an open question. 
We want the tokens to automatically be deleted after expiry time, which we want to set on some value like "one week". 

Our Android clients create a new token each time after logging out.

**Comment by kwaclaw** [comment]
What is the status of this now? It is late June 2019, and it looks like I still cannot register an Installation with a non-null expiration time. At least, reading it back indicates that my expiration time was ignored.

**Comment by spelluru** [comment]
#assign:jwargo

**Comment by spelluru** [comment]
@jwargo - Could you look into this issue? Thanks.

**Comment by jwargo** [comment]
@spelluru will do.

**Comment by jwargo** [comment]
@jodecler @CamSoper @kwaclaw The documentation is apparently incorrect, you can only `get` the value, not set it through the SDK. We'll update the docs. 

#please-close
