### ISSUE TITLE
Why are options = null when they are always required?

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-docs-sdk-dotnet#627]
When reading a document via ReadDocumentAsync, the API will always throw the following exception if a partition key is not supplied:

`"System.InvalidOperationException: PartitionKey value must be supplied for this operation."`

So, the request options parameter is always required for this READ operation - correct?

From: [https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.partitionkey?view=azure-dotnet#Microsoft_Azure_Documents_Client_RequestOptions_PartitionKey](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.partitionkey?view=azure-dotnet#Microsoft_Azure_Documents_Client_RequestOptions_PartitionKey),

> Partition key is used to identify the target partition for this request. It must be set on read and delete operations for all document requests

All of the examples shown for ReadDocumentAsync DO NOT include the request options parameter and thus would fail with the exception mentioned above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 655a6c50-b74a-c5d7-acbd-318abea552dc
* Version Independent ID: 8225efb0-e657-375c-7d71-d876793dcfcd
* Content: [DocumentClient.ReadDocumentAsync Method (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.readdocumentasync?view=azure-dotnet#Microsoft_Azure_Documents_Client_DocumentClient_ReadDocumentAsync__1_System_Uri_Microsoft_Azure_Documents_Client_RequestOptions_)
* Content Source: [xml/Microsoft.Azure.Documents.Client/DocumentClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
That's a good question. @mimig1 who should we route this to?

**Comment by mimig1** [comment]
@kirankumarkolli - Can you respond or route to the appropriate person?

**Comment by kirankumarkolli** [comment]
For partitioned collection this argument is always must. Best is to refresh the samples including the partitionkey while API gets fixed (which might take a while).

**Comment by CamSoper** [comment]
@bdcoder2 - You good? Can I close this?

**Comment by bdcoder2** [comment]
Sure – go ahead and close – thanks!
