### ISSUE TITLE
Timeout - infinite?

### ISSUE THREAD

**Issue by OlegKarasik** [Azure/azure-docs-sdk-dotnet#629]
What values should be supplied in order to set timeout to infinite and rely only on `CancellationToken`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a7a295a-a559-1460-56bf-e989f29b76a8
* Version Independent ID: 1526b116-1f54-eb07-f1d9-ada4e1c1705a
* Content: [FabricClient.QueryClient.GetServiceNameAsync(Guid, TimeSpan, CancellationToken) Method (System.Fabric)](https://docs.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient.queryclient.getservicenameasync?view=azure-dotnet#System_Fabric_FabricClient_QueryClient_GetServiceNameAsync_System_Guid_System_TimeSpan_System_Threading_CancellationToken_)
* Content Source: [xml/System.Fabric/FabricClient+QueryClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.Fabric/FabricClient+QueryClient.xml)
* Service: **service-fabric**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@msfussell @rwike77 Can you guys please help me answer this (or loop in someone who can)? 

Thanks!

**Comment by rwike77** [comment]
@oanapl  can you answer this one (or find someone who can)?  Thanks.

**Comment by oanapl** [comment]
Have you tried TimeSpan.MaxValue?

**Comment by OlegKarasik** [comment]
@oanapl 
> Have you tried TimeSpan.MaxValue?

I haven't because this probably would be 'request has very long time out' rather than 'this request never times out'.

Am I getting this right?

**Comment by oanapl** [comment]
This will never time out, since it's hard to wait for maxvalue :)

**Comment by OlegKarasik** [comment]
@oanapl 
>This will never time out, since it's hard to wait for maxvalue :)

My concern was mostly from the implementation standpoint. 

If something has time out value set then this should be tracked by the system (no matter what value is 1 second or 1000 years).

In this case if I would create 1.000.000 requests with the time out set to `TimeSpan.MaxValue` then system will track all this requests / consume resource / become less responsive.

The idea of **Infinite** time out is to instruct the system that no timeout tracking should be involved.

**Comment by oanapl** [comment]
Sorry, that is not supported. This is not really a problem, as the time tracking overhead is not big.

**Comment by OlegKarasik** [comment]
Is this functionality OpenSource?)

**Comment by oanapl** [comment]
https://github.com/Microsoft/service-fabric 
The managed part is not there yet, but we are working on exposing that too.

**Comment by OlegKarasik** [comment]
Can then the documentation be updated to specify at least that currently there is no way to specify infinite timeout value and user should always set real timeout value?

Some where in the **Remarks** section for example.

**Comment by OlegKarasik** [comment]
Accidentally clicked the wrong button.

**Comment by oanapl** [comment]
Like I said, for all purposes specifying TimeSpan.MaxValue is what people need to have "infinite" timeout. I don't see a need to have extra documentation on this case.

**Comment by OlegKarasik** [comment]
@oanapl 

> Like I said, for all purposes specifying TimeSpan.MaxValue is what people need to have "infinite" timeout. I don't see a need to have extra documentation on this case.

Initially the issue was created because from the documentation this isn't obvious that I should use `TimeSpan.MaxValue` in case I don't want to use timeout and want to rely only on `CancellationToken`. 

This really contradict with every other documentation from Microsoft where API exposes timeout support: [WaitForSingleObject()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms687032(v=vs.85).aspx), [AutoResetEvent.WaitOne()](https://msdn.microsoft.com/en-us/library/cc190477(v=vs.110).aspx).

Specifying such things in documentation are important. 

I personally, before submitting an issue have tried to pass `TimeSpan.Zero` and `TimeSpan(-1)`. Then I have passed large timeout value (to make things work) and went here on GitHub to get additional information about how to implement this in a right way.

That is why I don't agree with you regarding the need to document this. If documentation would have a note that infinite timeout isn't supported this would be more than enough to avoid this situation in future.

**Comment by oanapl** [comment]
Thank you for the detailed explanation. I will follow up on the documentation.

**Comment by OlegKarasik** [comment]
Hi @CamSoper.

Can you point me to the changes done in the docs?

**Comment by CamSoper** [comment]
I'm sorry, @OlegKarasik , I closed it because it seemed like @oanapl was making changes in the `///` comments that would be reflected automatically in the API browser. I generally bounce `///` things back over to the group that owns the API itself, since they're the ones who have to make that change. Would you like me to re-open it?

**Comment by OlegKarasik** [comment]
Yes. If this is possible can this issue be closed when changes would make their way in a docs sources? Otherwise it is hard to track :)

**Comment by OlegKarasik** [comment]
Hi @CamSoper. 
Looks like changes aren't reflected to the documentation page. Can you check please?

**Comment by CamSoper** [comment]
I'll look into it. 🙂 

@oanapl do you have a work item for this somewhere I can track?

**Comment by masnider** [comment]
@OlegKarasik @CamSoper - with TimeSpans, the .NET convention to achieve "wait forever" semantics is to use TimeSpan.MaxValue. This is [everywhere](https://github.com/dotnet/corefx/search?q=TimeSpan.MaxValue&unscoped_q=TimeSpan.MaxValue) in the .NET Framework. Please just do that. 

The APIs you've pointed to I agree are more clear in that they have a specific value for "forever" (as do other APIs like [Timeout](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timeout?view=netframework-4.7). But we're not dealing with Timeout, or with those other lower level APIs, (unfortunately). 

I'd agree with Oana that it's uncommon to really want to wait forever for these APIs to come back - that usually indicates that something else is wrong. Can you describe why you want to do this a little more? 

A case I have seen: Are you putting your "real" timeout into a different cancellation token source and then creating a token from that and passing that in? In general you'd only _need_ to do that if you were linking different sources together, and you could get much the same behavior but just setting the timeout timespan to the desired value. Is there some other reason you're interested in waiting "forever" here? 

Also - help us out! PR's are appreciated. I can try to come up with some language like "To rely only on the cancellation token to cancel the request, you may pass TimeSpan.MaxValue." but that feels like I'm just stating the obvious and I'm not sure it's what you're looking for. Is that it? Just stick that in the notes and you're good to go?

**Comment by OlegKarasik** [comment]
@masnider 
>A case I have seen: Are you putting your "real" timeout into a different cancellation token source and then creating a token from that and passing that in? In general you'd only need to do that if you were linking different sources together, and you could get much the same behavior but just setting the timeout timespan to the desired value. Is there some other reason you're interested in waiting "forever" here?

The scenario I found myself looking for `infinite` timeout was very simple. We have a kind of "gateway" that does multiple things including routing, request splitting etc. The thing here is that for outside world there is one endpoint and one request - but internally it can call multiple services, or can split the request between multiple partitions etc. So for all call that this service done there is no reasonable value to set - we rely on the "outer" cancellation token controlled by "outer" timeout.

>Also - help us out! PR's are appreciated. 

I thought the documentation is auto-generated that is why I wasn't sure where to look for it. If you can point me in the right direction it would be great.

>I can try to come up with some language like "To rely only on the cancellation token to cancel the request, you may pass TimeSpan.MaxValue." but that feels like I'm just stating the obvious and I'm not sure it's what you're looking for. Is that it? Just stick that in the notes and you're good to go?

The general idea is yes. The thing here is that usually when you have an API it rather accept the timeout or cancellation token. Accepting both it is a bit unusual. So the ideal solution from my point of view is to have additional overloads (only timeout, only cancellation token, current) - but I understand there can be a plenty of reasons why this cannot be done this way - but if it is possible I am ready to do this.

**Comment by CamSoper** [comment]
Closing the issue @OlegKarasik for reporting, but feel free to continue the conversation here.
