### ISSUE TITLE
What exactly does the PrefetchCount property control?

### ISSUE THREAD

**Issue by drub0y** [Azure/azure-docs-sdk-dotnet#632]
There is absolutely no documentation on this property and the name is too abstract to draw any specific conclusions from. It appears to me that this ends up setting `AmqpLinkSettings::TotalLinkCredit`, but that's an internal detail and, as such, there's no documentation on that either. This is problematic because, aside from this property not being documented, it is also a required constructor parameter in all but the most trivial overload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f795d29-d6a2-f088-bf1e-95ea7c67c895
* Version Independent ID: cfab7180-e642-2a45-b973-174ae9387ee9
* Content: [AmqpTransportSettings.PrefetchCount Property (Microsoft.Azure.Devices.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.amqptransportsettings.prefetchcount?view=azure-dotnet#Microsoft_Azure_Devices_Client_AmqpTransportSettings_PrefetchCount)
* Content Source: [xml/Microsoft.Azure.Devices.Client/AmqpTransportSettings.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/AmqpTransportSettings.xml)
* Service: **iot-hub**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@fsautomata @dominicbetts Can you please help me find some information for @drub0y?

Thank you!

**Comment by CamSoper** [comment]
@zolvarga @abhipsaMisra @yzhong94

**Comment by CamSoper** [comment]
Ping @fsautomata @dominicbetts @zolvarga @abhipsaMisra @yzhong94 - Anyone?

**Comment by AlexGhiondea** [comment]
@axisc can you help close the loop here?

**Comment by abhipsaMisra** [comment]
You are correct, the pre-fetch count is used to set the link credit over AMQP. What this signifies is the max. no. of messages that can be "in-flight" from the service to the client, at any given time. (This value defaults to 50 for the IoT Hub .NET client). 
The client specifies its link-credit, that the service must respect. In simplest terms, any time the service sends a message to the client, it decrements the link credit, and will continue sending messages until linkCredit > 0. Once the client acknowledges the message, it will increment the link credit.
