### ISSUE TITLE
ExecuteBatchAsync(TableBatchOperation, CancellationToken) is missing

### ISSUE THREAD

**Issue by sguryev** [Azure/azure-docs-sdk-dotnet#635]
I'm using `WindowsAzure.Storage` Nuget package version 9.1.1 https://www.nuget.org/packages/WindowsAzure.Storage/

I can't find the `ExecuteBatchAsync(TableBatchOperation, CancellationToken)` method there.
Is it removed now?

![image](https://user-images.githubusercontent.com/6978458/40023578-2fd51138-57d4-11e8-9c9b-6eb864a5dcfe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f39539-0da7-7b1c-caab-3e3b484f0410
* Version Independent ID: 7f9c1154-1bfe-b8e5-c2bb-d5842200f4d8
* Content: [CloudTable.ExecuteBatchAsync Method (Microsoft.WindowsAzure.Storage.Table)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.cloudtable.executebatchasync?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Table_CloudTable_ExecuteBatchAsync_Microsoft_WindowsAzure_Storage_Table_TableBatchOperation_System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Table/CloudTable.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Table/CloudTable.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
As far as I can tell, [the method signature is still valid](https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/ClassLibraryCommon/Table/CloudTable.cs#L230).

@tamram Do you happen to know if there's been a change there?

**Comment by mirobers** [comment]
This specific overload is not available in the netstandard version of the package. Please use the overload with request options and operation context instead, or target .NET Framework.

**Comment by sguryev** [comment]
Yep sorry, it's a .net core and netstandart. May I use the default constructed objects for request options and operation context or should I specify some values? Are you going to add this note to the doc?

**Comment by mirobers** [comment]
You can pass null for these parameters. We're going to release netstandard 2.0 support soon, which will bring parity with .NET Framework (and the docs).
