### ISSUE TITLE
ExecuteNextAsync behavior unclear (see second comment)

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-docs-sdk-dotnet#638]
The markup tags are displayed rather than being rendered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3411ea-4b30-753c-aaac-7d99e19fd995
* Version Independent ID: 8a66c3a5-ba47-6b3d-6cf9-72c4608830ac
* Content: [DocumentQueryable.AsDocumentQuery(IQueryable<T>) Method (Microsoft.Azure.Documents.Linq)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.linq.documentqueryable.asdocumentquery?view=azure-dotnet#Microsoft_Azure_Documents_Linq_DocumentQueryable_AsDocumentQuery__1_System_Linq_IQueryable___0__)
* Content Source: [xml/Microsoft.Azure.Documents.Linq/DocumentQueryable.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/DocumentQueryable.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by bdcoder2** [comment]
Also, please add the following to the documentation -- which after nearly two days of trying to get pagination working, I found this gem which should be in docs.microsoft.com:

From: [https://stackoverflow.com/questions/42866896/executenextasync-not-working](https://stackoverflow.com/questions/42866896/executenextasync-not-working)

Individual calls to **ExecuteNextAsync** may return 0 results, but when you run the query to completion by calling it until **HasMoreResults** is false, you will always get the complete results.

Almost always, a single call to **ExecuteNextAsync** will return results, but you may get 0 results commonly due to two reasons:

1.  If the query is a scan, then DocumentDB will make partial progress based on available throughput.  Here no results are returned, but a new continuation token based on the latest progress is returned to resume execution.

2. If a cross-partition query, then each call executes against a single partition. In this case, the call will return no results if that partition has no documents that match the query.

If you want queries to deterministically return results, you must use SELECT TOP vs. using the continuation token/ExecuteNextAsync as a mechanism for paging. You can also read query results in 
 parallel across multiple partitions by changing FeedOptions.**MaxDegreeOfParallelism** to -1.

**Comment by CamSoper** [comment]
All excellent feedback! Thank you!

@mimig1 Should I open an issue in VSTS reflecting this?

**Comment by mimig1** [comment]
@CamSoper - I will defer to @SnehaGunda on this, she now owns Azure Cosmos DB docs. Thanks!

**Comment by CamSoper** [comment]
Ping @SnehaGunda for visibility before I close this. Sneha, how shall we proceed?

**Comment by SnehaGunda** [comment]
@CamSoper thanks working with the SDK team to integrate the feedback.

**Comment by chojrak11** [comment]
Any chance of improving the docs? I also stumbled upon this problem when querying Cosmos DB.

**Comment by AlexGhiondea** [comment]
@SnehaGunda can this be closed?

**Comment by Hermholtz** [comment]
Has it been fixed? Seeing no commits I don't think so. Please fix the docs and only then close it.

**Comment by AlexGhiondea** [comment]
@Hermholtz I'm trying to figure out if the docs have been fixed or not 🙂. @SnehaGunda was following up on that a while back which I why I pinged them.

It also looks like the original issue of rendering has been addressed and the piece that is left is the one around additional documentation.

**Comment by SnehaGunda** [comment]
@kirankumarkolli  @ealsur can you please look into this issue?

**Comment by ealsur** [comment]
The API example is basically showing what it's requested, that the query is drained until HasMoreResults is false.

The V3 SDK also has the same examples: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.feediterator?view=azure-dotnet#examples

The mention of empty pages is in the docs too: https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-query-performance#common-sdk-issues

![image](https://user-images.githubusercontent.com/1633401/106677840-56ae3f00-656e-11eb-9a30-fe81f5489b2c.png)

**Comment by jsquire** [comment]
Closing this out based on @ealsur's findings that the requested information is present.   Please feel free to reopen if you believe that further discussion is needed.

**Comment by Hermholtz** [comment]
If you just put only one sentence in the referred document instead of spending much more energy on writing multiple sentences in your multiple comments to prove that this ticket is not worth fixing, it would bring more benefits for future readers. How awesome.

The below (in the more doc-friendly language) would suffice:

> NOTE: The individual calls to ExecuteNextAsync can return 0 results, but that's okay, just iterate until HasMoreResults is false.
