### ISSUE TITLE
DateFormatString property of JsonSerializerSettings

### ISSUE THREAD

**Issue by antoanela** [Azure/azure-docs-sdk-dotnet#645]
Hi, I'm trying to use the LoadFrom method with a custom DateFormatString and the format I set is being ignored. What is the correct way to use it?

            var serializerSettings = new JsonSerializerSettings()
            {
                DateFormatString = "yyyy'-'MM'-'dd'T'HH':'mm':'ssZ",
            };
            var doc = new Document();
            doc.LoadFrom(jsonReader, serializerSettings);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba672832-1852-010b-4c26-aa771cc5afc4
* Version Independent ID: 2ae5d4ef-c46d-fe03-4213-1cd4886d608c
* Content: [JsonSerializable.LoadFrom Method (Microsoft.Azure.Documents)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.jsonserializable.loadfrom?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents/JsonSerializable.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents/JsonSerializable.xml)
* Service: **cosmos-db**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by mimig1** [comment]
@antoanela - Have you looked through this article for an answer? https://docs.microsoft.com/en-us/azure/cosmos-db/working-with-dates 
If that doesn't help, @SnehaGunda can investigate.

**Comment by antoanela** [comment]
Thanks, but that doesn't solve the problem. What I want to achieve is keep the trailing 0's in the date string, so I'm trying to set a format ending with .fff. Unfortunately the LoadFrom method continues to strip the 0's. 

The default DateFormatString used by JsonSerializerSettings seems to be yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK, and although that is successfully overridden in my object, the LoadFrom method seems to ignore it.

**Comment by SnehaGunda** [comment]
@antoanela unfortunately I haven't had a chance to play with date variables yet, so I can't help you but can you please send an email to "askcosmosdb@microsoft.com" so that it gets visibility and response from broader audience? please let me know if that doesn't work, I can investigate internally with our team and get back to you.
