### ISSUE TITLE
Cosmos DB Docs spelling error in extension method (see comments)

### ISSUE THREAD

**Issue by dbiehle** [Azure/azure-docs-sdk-dotnet#646]
at description of IsPrimitive(Object)
"Determines if a certain property is of _premitive_ JSON type."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9da3b1-4d17-5d3b-0fa3-b33e2f74f548
* Version Independent ID: 901632ad-c1b5-4a44-797e-817514621b88
* Content: [OperationContext Class (Microsoft.ApplicationInsights.Extensibility.Implementation)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.implementation.operationcontext?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationContext.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationContext.xml)
* Service: **application-insights**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Turns out the spelling issue is not in the Application Insights API, it's downstream from the Cosmos DB API. See here:  https://github.com/Microsoft/ApplicationInsights-dotnet/issues/843#issuecomment-404575174

@SnehaGunda can you please help me track this down?

**Comment by SnehaGunda** [comment]
@CamSoper making sure I understand this correctly, I think the issue corresponds to a typo which need to be fixed in one of the assemblies: Microsoft.Azure.DocumentDB.Core.dll or Microsoft.Azure.Documents.Client.dll correct?

Where is the source code repo/file for this? I can show share that with the dev team and ask to fix it in the source code.

**Comment by CamSoper** [comment]
@SnehaGunda Correct, it's where ever [this extension method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.systemfunctions.typecheckfunctionsextensions.isprimitive?view=azure-dotnet#Microsoft_Azure_Documents_SystemFunctions_TypeCheckFunctionsExtensions_IsPrimitive_System_Object) lives, but I haven't opened the assembly up in Class Browser to figure out where that is.

I was hoping you'd know who to take it to!  😆 Who's the PM you work with on that team?

**Comment by SnehaGunda** [comment]
@CamSoper I will initiate a thread with the .Net SDK PM contact (will cc you on the thread)

**Comment by AlexGhiondea** [comment]
@SnehaGunda has this been resolved?

**Comment by jsquire** [comment]
Closing; the referenced extension method is no longer appearing in for the associated content.   Please feel free to reopen if you believe that further discussion is needed.
