### ISSUE TITLE
Shared access signature needed

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-docs-sdk-dotnet#650]
It would be helpful to add to the documentation that shared access signatures are often needed.
I wasted a lot of time trying to resolve a 404 error that StartCopyAsync was throwing.
Although I had created two CloudBlockBlob objects (for the source and target) and even though I could read the properties of both via those blob objects, change the content of both, etc, this was still insufficient for an async copy.  For an async copy I had to pass a Uri for the source that contained a shared access signature.  This was presumably because my source and targets were in two different storage accounts.  It would be helpful if this was noted in the documentation.  For more details and an example, I found the following blog post helpful:
https://alexandrebrisebois.wordpress.com/2013/06/25/copy-blobs-with-startcopyfromblob-and-track-its-progression-using-copystate/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aeaf380-0c39-8d13-8e53-6236cbc81817
* Version Independent ID: 76f22981-df94-3d74-234b-24a712ffb1da
* Content: [CloudBlockBlob.StartCopyAsync Method (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblockblob.startcopyasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlockBlob.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlockBlob.xml)
* Service: **storage**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Thank you for the feedback!  I'll pass this to the developers.
