### ISSUE TITLE
Parameterに指定できる言語

### ISSUE THREAD

**Issue by hatsunea** [Azure/azure-docs-sdk-dotnet#653]
ParameterにはBCP-47 formatで音声認識する言語を指定することになっているが、Speech Serviceが対応している言語の一覧へのリンクがないと実際の指定値がわからない

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9479385b-3c2c-b046-74db-f3ae177410bc
* Version Independent ID: 9287d79f-fdad-65d1-422e-4d05d6dc9559
* Content: [SpeechFactory.CreateSpeechRecognizer Method (Microsoft.CognitiveServices.Speech)](https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.cognitiveservices.speech.speechfactory.createspeechrecognizer?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.CognitiveServices.Speech/SpeechFactory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech/SpeechFactory.xml)
* Service: **unspecified**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Attn: @wolfma61 @v-jerkin @nitinme @mahilleb-msft 

Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted this issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. 

Translated from Japanese (via Bing) the comment is:

> parameter is supposed to specify a language for speech recognition in the BCP-47 format, but the Speech service does not know the actual specified value without a link to the list of supported languages.

Can you guys help me get an issue created to improve the inline XML docs?

**Comment by wolfma61** [comment]
the list of supported languages is part of the SDK Reference Documentation.
See here: 
https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/supported-languages

Wolfgang
