### ISSUE TITLE
Notification Hub - Expand management API example

### ISSUE THREAD

**Issue by michelejohlbs** [Azure/azure-docs-sdk-dotnet#655]
Sad to say, but the documentation is extremely poor and lacking of examples on the management libraries.
I was directed to this page from https://docs.microsoft.com/en-gb/azure/notification-hubs/ with a link stating "Create notification hub - .NET" under the how-to guides, but I fail to see the details for the creation of a notification hub or any examples.
The explore management APIs is not any help either.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80aceb4a-a9b0-05bf-8c02-fe349e4bf6a2
* Version Independent ID: 9704b52e-c74b-fbc1-a35d-d684efeabc50
* Content: [Azure Notification Hubs libraries for .NET](https://docs.microsoft.com/en-gb/dotnet/api/overview/azure/notification-hubs?view=azure-dotnet#feedback)
* Content Source: [api/overview/azure/notification-hubs.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/notification-hubs.md)
* Service: **notification-hubs**
* Product: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Oh, I'm so sorry! I misunderstood the comment and closed it. I'm sorry, I was going through a lot of these this afternoon.

Okay, I see what you're saying now. The Notification Hubs doc referred you to this doc under "how-to," but you're confused as to why there's no how-to information here. This is the reference documentation for the .NET API for managing notification hubs, and doesn't generally have much in the way of "conceptual" content (e.g., how-tos and tutorials). It doesn't mean we can't create it if we need to - but we are constrained by resources and have to prioritize.

What are you trying to do? Maybe I can help you or get you in touch with someone who can.

**Comment by michelejohlbs** [comment]
Thank you @CamSoper

**Comment by jwargo** [comment]
Please close this, nothing actionable anymore (more than a year later)
