### ISSUE TITLE
NameValidator validation rules & behavior

### ISSUE THREAD

**Issue by gumgl** [Azure/azure-docs-sdk-dotnet#656]
You can find the precise rules for validation [here](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata).
Also, this documentation is not clear on what behavior should be expected from `NameValidator.Validate*` methods since they are all of `void` return types. Short answer: they throw `ArgumentException`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2d8a79-5ce7-6f40-de84-8912cd094f57
* Version Independent ID: fbb8d787-a291-45d5-8c0f-0071918090f9
* Content: [NameValidator Class (Microsoft.WindowsAzure.Storage)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.namevalidator?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage/NameValidator.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage/NameValidator.xml)
* Service: **storage**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Thank you so much for sorting that!

**Comment by gumgl** [comment]
Sorry what? I didn't sort/resolve anything, it looks like the documentation hasn't changed.
