### ISSUE TITLE
Type does not match the value listed in the "Dependencies" table in AppInsights

### ISSUE THREAD

**Issue by skoon** [Azure/azure-docs-sdk-dotnet#658]
When I implement an ITelemetryProcessor and attempt to check the Type property of a DependencyTelemetry object, the value is always equal to "Http", but the value stored in AppInsights is "Azure queue" or "Azure blob" or some other value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc51e7a-abcc-d40c-9764-e747b464e582
* Version Independent ID: db919e8b-038a-c317-8167-9f2d10c65deb
* Content: [DependencyTelemetry.Type Property (Microsoft.ApplicationInsights.DataContracts)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.dependencytelemetry.type?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml)
* Service: **application-insights**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Hi, Scott! Followed you on Twitter for a long time.

I'm closing this and opening it again in the AppInsights repo, as they're the ones who are going to have to clarify the ref docs.

Glad to meet you!
