### ISSUE TITLE
How to retrieve Runbook job?

### ISSUE THREAD

**Issue by MortenMeisler** [Azure/azure-docs-sdk-dotnet#659]
Should be as simple as this right?

```
//Get job by jobname (which is the jobId)
var job = client.Job.Get("my resource group name", "my automation account name", "38ff75c2-d4ca-471f-b4a5-2a98da4d252b");
```

I'm getting error: 
1/2:
JsonSerializationException: Error converting value "Succeeded" to type 'Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty'. Path 'properties.provisioningState', line 1, position 427

2/2:
ArgumentException: Could not cast or convert from System.String to Microsoft.Azure.Management.Automation.Models.JobProvisioningStateProperty.

This one works fine:
`var jobs = client.Job.ListByAutomationAccount(resourceGroup, automationAccount);`

And from that list of jobs I can check the names

What is the syntax here? any examples?

Thanks

Using preview version 3.0.3 (which was the least painfull to get authenticated with :)).

**Comment by CamSoper** [comment]
I recently had reason to wrestle with the 3.0.3 version of the automation library. I agree, it's rough. Let's see what they say.

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-sdk-for-net #4478](https://github.com/Azure/azure-sdk-for-net/issues/4478) via [**ZenHub**](https://www.zenhub.com/)
