### ISSUE TITLE
is it really obsolete?

### ISSUE THREAD

**Issue by wayne-kim** [Azure/azure-docs-sdk-dotnet#664]
This API is now obsolete. However, it is used in conjunction with the newly reorganized API.
i'm really confused.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 5c0dfb0e-e35d-dee1-1f5a-e6033173ae1d
* Version Independent ID: bfb5d58f-6f67-82b3-82c3-de42bd5f4559
* Content: [IChangeFeedObserver Interface (Microsoft.Azure.Documents.ChangeFeedProcessor)](https://docs.microsoft.com/ko-kr/dotnet/api/microsoft.azure.documents.changefeedprocessor.ichangefeedobserver?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents.ChangeFeedProcessor/IChangeFeedObserver.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.ChangeFeedProcessor/IChangeFeedObserver.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
I'm sorry, can you please restate the question? The API is still supported, I believe.

**Comment by wayne-kim** [comment]
Someone seems to have modified it.

It is stated that this API will not be used at level 28. However, it was used with the 28 level API in a official Sample. So I was confused.
