### ISSUE TITLE
Seemingly wrong description

### ISSUE THREAD

**Issue by ali-nazem** [Azure/azure-docs-sdk-dotnet#668]
"Time when the message was received by the server" seems to be an irrelevant description for a property called "DeliveryCount".
It looks like this description was copy pasted from the description of "EnqueuedTimeUtc" property, hence still unclear what DeliveryCount property provides.

Best regards, 
Ali

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e589d5-b37d-c203-794e-edb04529240a
* Version Independent ID: a9d44046-5cbb-5ace-835d-26c797dd9709
* Content: [Message.DeliveryCount Property (Microsoft.Azure.Devices.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.message.deliverycount?view=azure-dotnet#Microsoft_Azure_Devices_Client_Message_DeliveryCount)
* Content Source: [xml/Microsoft.Azure.Devices.Client/Message.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/Message.xml)
* Service: **iot-hub**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Issue moved to [Azure/azure-iot-sdk-csharp #531](https://github.com/Azure/azure-iot-sdk-csharp/issues/531) via [**ZenHub**](https://www.zenhub.com/)
