### ISSUE TITLE
DataFactoryManagementClient does not work with .Net Core

### ISSUE THREAD

**Issue by vulbecula** [Azure/azure-docs-sdk-dotnet#683]
There is no clear indication that this is not .Net Core compatible.
If you try to use this with .Net Core you will see runtime "Could not load file or assembly xxx" errors. That point to .Net Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbf40d3-9b53-469b-2ba2-99bea8d5188e
* Version Independent ID: 6234bcb9-58a9-69e0-6ea2-375d12eacb0b
* Content: [Microsoft.Azure.Management.DataFactories Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactories?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Azure.Management.DataFactories.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.Management.DataFactories.xml)
* Service: **data-factory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Which NuGet package are you using?  I see the [latest package](https://www.nuget.org/packages/Microsoft.Azure.Management.DataFactory/0.8.0-preview) has dependencies on both .NET Standard and Framework.
