### ISSUE TITLE
Consider linking to/documenting the paramaterized query syntax from SqlQuerySpec

### ISSUE THREAD

**Issue by chwarr** [Azure/azure-docs-sdk-dotnet#689]
I need to know how to construct a parameterized query for the "QueryText" parameters. It would be nice if this documentation linked to [the documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query#parameterized-sql-queries) for parameterized queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1edc6a2f-a3b9-7d37-c58a-bc4070651421
* Version Independent ID: 0148ad01-c798-9fe5-8a35-fd3ae918b1bb
* Content: [SqlQuerySpec Class (Microsoft.Azure.Documents)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.sqlqueryspec?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents/SqlQuerySpec.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents/SqlQuerySpec.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing this out;  this version of the Cosmos library has been superseded and is only receiving critical fixes and the associated article is also marked as deprecated.  This requires a code change that is unlikely to be made.  Please feel free to reopen if you believe that further discussion is needed.
