### ISSUE TITLE
No documentation on what happens in a failure situation

### ISSUE THREAD

**Issue by rocifier** [Azure/azure-docs-sdk-dotnet#694]
How can I detect a failure in obtaining the token? Is a null value returned? Are exceptions returned eg. if there is a timeout or if you are not authorized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13072510-d092-6225-c5c1-637ce33936fd
* Version Independent ID: 85305d5b-a202-0e47-d9b0-78eefad2c50e
* Content: [AuthenticationContext.AcquireTokenAsync Method (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_System_String_System_Uri_Microsoft_IdentityModel_Clients_ActiveDirectory_IPlatformParameters_Microsoft_IdentityModel_Clients_ActiveDirectory_UserIdentifier_System_String_)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Hi there, @rocifier! I don't know the answer to your question, but I've [forwarded the question](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1110) to the maintainers of the project.

Please let me know if you don't hear back from them and I'll follow-up.

**Comment by rocifier** [comment]
No worries, I've found so far that null can be returned. It is more valuable to the community to improve the documentation to explain exception situations.
