### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sehcheese** [Azure/azure-docs-sdk-dotnet#706]
The link is missing a "/".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba86803-405b-8aac-88cd-887fadb36391
* Version Independent ID: c57a141f-9b9f-a9e7-8947-ecdee47bd151
* Content: [RequestOptions.OfferType Property (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.offertype?view=azure-dotnet#Microsoft_Azure_Documents_Client_RequestOptions_OfferType)
* Content Source: [xml/Microsoft.Azure.Documents.Client/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by myrsnipa** [comment]
o

**Comment by alohaninja** [comment]
`http://azure.microsoft.comdocumentation/articles/documentdb-performance-levels/` should be `http://azure.microsoft.com/documentation/articles/documentdb-performance-levels/`

**Comment by jsquire** [comment]
Closing this out;  this version of the Cosmos library has been superseded and is only receiving critical fixes and the associated article is also marked as deprecated.  This requires a code change that is unlikely to be made.  Please feel free to reopen if you believe that further discussion is needed.
