### ISSUE TITLE
No Example Given for the method

### ISSUE THREAD

**Issue by Pranshu258** [Azure/azure-docs-sdk-dotnet#711]
Please add an example for this method, required arguments and correct usage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efb3ddb-2c90-c1f7-eba9-f1c61c7f8203
* Version Independent ID: 1013e00a-d357-2391-7202-d57bb7fa785a
* Content: [TableOperation.Replace(ITableEntity) Method (Microsoft.WindowsAzure.Storage.Table)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.tableoperation.replace?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Table/TableOperation.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Table/TableOperation.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jasonshave** [comment]
@CamSoper is it possible to get someone to write an example here? I need one too :)

**Comment by CamSoper** [comment]
I absolutely hear you. I'll bump up the priority a bit.

**Comment by AlexGhiondea** [comment]
@CamSoper has this been resolved?

**Comment by jsquire** [comment]
Closing; the referenced content is no longer available.  (page 404)
