### ISSUE TITLE
code seems to be double encoded 

### ISSUE THREAD

**Issue by SimonCropp** [Azure/azure-docs-sdk-dotnet#713]
![image](https://user-images.githubusercontent.com/122666/42685928-bae064a8-86d7-11e8-9447-6d9447cce543.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c3411ea-4b30-753c-aaac-7d99e19fd995
* Version Independent ID: 8a66c3a5-ba47-6b3d-6cf9-72c4608830ac
* Content: [DocumentQueryable.AsDocumentQuery(IQueryable&lt;T&gt;) Method (Microsoft.Azure.Documents.Linq)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.linq.documentqueryable.asdocumentquery?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Documents.Linq/DocumentQueryable.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Linq/DocumentQueryable.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Hey there! Thanks for reporting this. It's a known issue with how the site is rendering the XML content, and it's being worked on by the appropriate people. 

Here's the duplicate issue for reference: https://github.com/Azure/azure-docs-sdk-dotnet/issues/615

Thanks again!
