### ISSUE TITLE
reg analysis server

### ISSUE THREAD

**Issue by NambiVenkatesh** [Azure/azure-docs-sdk-dotnet#716]
can this same property be used to retrieve sql analysis servers as well? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef2d29c-1c1e-f9c9-8224-2e61cef002ae
* Version Independent ID: 09c6f52b-7aaa-f311-fb33-7e2fdac7ece3
* Content: [Azure.SqlServers Property (Microsoft.Azure.Management.Fluent)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.fluent.azure.sqlservers?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Management.Fluent/Azure.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Fluent/Azure.xml)
* Service: **service-bus**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@NambiVenkatesh No, it's actually for [Azure SQL Database](https://docs.microsoft.com/azure/sql-database/sql-database-technical-overview), which is a serverless platform-as-a-service offering.
