### ISSUE TITLE
Remarks for PagedEnumerableExtensions.ForEachAsync overloads are formatted incorrectly

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-docs-sdk-dotnet#722]
For each of the three overloads of ForEachAsync&lt;T&gt; listed here, the second half of the "Remarks" text is formatted incorrectly as a code block, like this:

---

### Remarks

This method processes elements sequentially, not concurrently. That is, for each element in the

    sequence, the method awaits the asynchronous delegate before processing the next element.

---

I'd expect the content to be presented this way:

---

### Remarks

This method processes elements sequentially, not concurrently. That is, for each element in the
sequence, the method awaits the asynchronous delegate before processing the next element.

---

Looking at the source code (in [PagedEnumerableExtensions.cs](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Batch/DataPlane/Azure.Batch/PagedEnumerableExtensions.cs)), the `<remarks>` tag in the xml documentation is formatted correctly, so I'd speculate that the parser that builds this page isn't correctly handling the text content of the tag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e888ac-9eb0-b188-19d9-48abb7604880
* Version Independent ID: 3a5044a3-0fd5-bc03-beda-435284ff69ad
* Content: [PagedEnumerableExtensions.ForEachAsync Method (Microsoft.Azure.Batch)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.pagedenumerableextensions.foreachasync?view=azure-dotnet#Microsoft_Azure_Batch_PagedEnumerableExtensions_ForEachAsync__1_Microsoft_Azure_Batch_IPagedEnumerable___0__System_Action___0__System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.Azure.Batch/PagedEnumerableExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Batch/PagedEnumerableExtensions.xml)
* Service: **batch**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Hey there! Thanks for reporting this. It's a known issue with how the site is rendering the XML content, and it's being worked on by the appropriate people. 

Here's the duplicate issue for reference: https://github.com/Azure/azure-docs-sdk-dotnet/issues/615

Thanks again!

**Comment by theunrepentantgeek** [comment]
Thanks for the update and the link.
