### ISSUE TITLE
Bad Documentation

### ISSUE THREAD

**Issue by MarkArranz** [Azure/azure-docs-sdk-dotnet#726]
As a first time user of Notification Hub it is incredibly frustrating when I go to the documentation and the property names are defined by simply restating the property name and class name again in a sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab362259-8f50-07aa-e49e-459f6193eceb
* Version Independent ID: 69c21701-3e16-487f-4ef3-f929b742968c
* Content: [NotificationOutcome.Results Property (Microsoft.Azure.NotificationHubs)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.notificationoutcome.results?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/NotificationOutcome.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/NotificationOutcome.xml)
* Service: **notification-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
I agree, that's a pretty frustrating experience. I'll take this as a backlog item to get the API developers to expand those definitions.

**Comment by MarkArranz** [comment]
Please let me know if there is anything I can do to help. I’d be more than happy to contribute to the Notification Hub documentation overall. I’ve had to black box test it over the past few weeks to get everything working and have taken notes along the way.

**Comment by CamSoper** [comment]
@dimazaid Do you have a public repo for this package? We've got a few issues where a more descriptive XML docs would be really useful, and community members like @MarkArranz who would be happy to help.

**Comment by jwargo** [comment]
@MarkArranz I'm sorry for the amazingly late response to this, we didn't get this issue until a few days ago. As I understand it, that documentation is generated from source - the SDK is open source, we're happy to have customers make changes and submit them as a PR.

**Comment by jwargo** [comment]
@MarkArranz I've created a bug to have our Engineering team fix this. Thanks for pointing it out.
