### ISSUE TITLE
409 response?

### ISSUE THREAD

**Issue by kkurkowski** [Azure/azure-docs-sdk-dotnet#729]
Why return a 409 response if the document id already exists?  The entire point of an upsert operation is that it should update/replace if the record already exists.  This documentation is contradicted with https://azure.microsoft.com/en-us/blog/documentdb-adds-upsert/ which states the response will be 200 (if replace) or 201 (if insert).  Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45869e83-3f4b-0c94-56f1-b24004a3e11f
* Version Independent ID: 47cf385f-fa58-534d-adb3-7a3dec463a44
* Content: [DocumentClient.UpsertDocumentAsync Method (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.upsertdocumentasync?view=azure-dotnet#definition)
* Content Source: [xml/Microsoft.Azure.Documents.Client/DocumentClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/DocumentClient.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@kkurkowski That list of status codes appears to be the full list of possible codes for the [DocumentClientException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.documentclientexception?view=azure-dotnet) property. Upsert should not ever return a 409, though it can certainly be returned on an Insert.

**Comment by merric-rocketpartners** [comment]
I'm seeing a 409 on upsert:


com.microsoft.azure.documentdb.DocumentClientException: Entity with the specified id already exists in the system.,
RequestStartTime: 2020-04-29T13:58:13.5298355Z, RequestEndTime: 2020-04-29T13:58:13.5298355Z,  Number of regions attempted:1
ResponseTime: 2020-04-29T13:58:13.5298355Z, StoreResult: StorePhysicalAddress: rntbd://dm5prdddc01-docdb-1.documents.azure.com:14128/apps/a8955ea6-38e2-4f3d-b7ae-bcbfaea92dce/services/730de375-bd04-42fc-a7f3-94eb34626553/partitions/4afd492a-3c42-4014-a020-0021600b6d24/replicas/132305339029504459p/, LSN: 2, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 1.67, ItemLSN: -1, SessionToken: -1#2, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert
, Microsoft.Azure.Documents.Common/2.10.0, StatusCode: Conflict

**Comment by vadim-kor** [comment]
409 is not only about unique ID. It's also about unique field constraints.  
You can define unique fields set when you create a collection. 

So you will get 409 if you try to replace an item with a value used by another item in this collection within this partition.

**Comment by merric-rocketpartners** [comment]
@vadim-kor Very true. That did not apply in my case. In fact, I saw through the console that ANY time I tried to submit ANY payload with an existing PARTITION Id I saw a 409. That is I could not have 2 records of the same partition id. I could also only have 1 record with NO partition id. This persisted until I deleted and recreated the container. It is lucky I did not experience this in production.

**Comment by stoicalpirate** [comment]
@vadim-kor apologies for reviving this old thread, but I'm having this exact same issue. As soon as I apply unique key constraints I start getting 409 errors despite there being no conflicting keys that I can see. I've even gone into the Portal and attempted to add a simple record with a single datapoint (along with an id and the partition key) and I still get a 409 exactly as @merric-rocketpartners mentioned.
