### ISSUE TITLE
Repetitive Descriptions

### ISSUE THREAD

**Issue by DeanGross** [Azure/azure-docs-sdk-dotnet#731]
Many of the descriptions for the methods are the same, it would be much more helpful if the descriptions were unique for each method so that inexperienced users would have a better understanding of how each method should be used. They are non intuitively obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84846d44-79c3-e8fa-8dab-f52758cff295
* Version Independent ID: b0f4e41d-a2a8-0cd8-a74a-c1ae436536b6
* Content: [AuthenticationContext Class (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/AuthenticationContext.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Are you referring to how all those overloads (which are the same function, but with different signatures) have the same basic descriptions? Can you help me understand an example of how this could be improved?

**Comment by DeanGross** [comment]
Yes, the overloads take different parameters so it would be helpful if the descriptions provided some information about the strings that can be used. Seeing that it takes two strings without information about what those strings are supposed to be does not tell us what we should pass into the method.

**Comment by AlexGhiondea** [comment]
@DeanGross I believe each of the parameters and methods have additional details once you click on them. I think having all that information on the same page would clutter the page too much.

Please let me know if you disagree.

**Comment by jsquire** [comment]
Closing based on @AlexGhiondea's investigation of the current state.  Please feel free to reopen if you feel that further discussion is needed.
