### ISSUE TITLE
Enumerating Installations

### ISSUE THREAD

**Issue by aschultz** [Azure/azure-docs-sdk-dotnet#732]
There doesn't seem to be any way to query for or enumerate Installations. How is a backend service expected to perform updates to Installations without maintaining a database of identifiers and calling GetInstallation on each one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 267bf520-19e9-a4f0-1128-d09471dc5aa1
* Version Independent ID: 76584903-5ff3-8ed5-1dfa-45061afa0c78
* Content: [NotificationHubClient Class (Microsoft.Azure.NotificationHubs)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.notificationhubclient?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/NotificationHubClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/NotificationHubClient.xml)
* Service: **notification-hubs**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@dimazaid ?

**Comment by jwargo** [comment]
@aschultz this is described here: https://docs.microsoft.com/en-us/azure/notification-hubs/export-modify-registrations-bulk. You move the registrations into a separate database, update them, import them back in. #please-close

**Comment by jwargo** [comment]
@aschultz I'm sorry, that's for registrations. There is no bulk update option for installations but this is something we have on our roadmap.

**Comment by jwargo** [comment]
@CamSoper please close, this functionality doesn't exist today.
