### ISSUE TITLE
API Not supported in .Net Core

### ISSUE THREAD

**Issue by VohuMana** [Azure/azure-docs-sdk-dotnet#733]
This API is not supported in .Net Core as found in this GitHub issue: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/879

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a1f25-5d64-60b4-82a3-753c6161e5e0
* Version Independent ID: 4b9d73c3-29d5-da07-4a42-f858cca03c5d
* Content: [PlatformParameters Class (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.platformparameters?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/PlatformParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/PlatformParameters.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by arraisgabriela** [comment]
Hi, is there any solution for this? I am trying to use it, unsuccessfully.

**Comment by AlexGhiondea** [comment]
@arraisgabriela it looks like there is an available package with .NET Standard support now. Is that API not available in the package?

**Comment by jsquire** [comment]
Closing this out;  there is now an available package with .NET Standard support.   Please feel free to reopen if you believe that further discussion is needed.
