### ISSUE TITLE
Question: SqlConnection object is cached?

### ISSUE THREAD

**Issue by kazshi** [Azure/azure-docs-sdk-dotnet#737]
I received the following question from my customer.  Thanks.
Is the returned SqlConnection object cached and reused for future connections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8933d36b-32d2-5bdd-ee9c-e85f055260b7
* Version Independent ID: 686bc694-a5de-7e41-1ebb-19062f514331
* Content: [ShardMap.OpenConnectionForKey Method (Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.sqldatabase.elasticscale.shardmanagement.shardmap.openconnectionforkey?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement/ShardMap.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement/ShardMap.xml)
* Service: **sql-databse**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
All SqlConnection objects participate in [connection pooling](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling?view=netframework-4.7.2) by default.
