### ISSUE TITLE
Typo in Examples Section

### ISSUE THREAD

**Issue by royshea** [Azure/azure-docs-sdk-dotnet#739]
Looks like the "Examples" section contains two copies of the same paragraph and example block.  Copy and paste error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc4b490-cde5-22d7-4f47-26c2ad2e1032
* Version Independent ID: 5edcf35b-4224-e0e2-2bc4-cc599681ef7e
* Content: [RequestOptions.PartitionKey Property (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.partitionkey?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Documents.Client/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing this out;  I'm no longer seeing duplication in the examples.   Please feel free to reopen if you believe that further discussion is needed.
