### ISSUE TITLE
The link to service life-cycle page isn't a link

### ISSUE THREAD

**Issue by OlegKarasik** [Azure/azure-docs-sdk-dotnet#740]
In the documentation there is a link to service life-cycle page but it is rendered as text rather than as link.

> For information about Reliable Services life cycle please see `https://docs.microsoft.com/azure/service-fabric/service-fabric-reliable-services-lifecycle`

Is this possible to make it to be a link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c445299-9524-48b3-3569-7a5ab9541468
* Version Independent ID: e027b46e-52c3-fc96-fa0b-616d218ff870
* Content: [StatefulService Class (Microsoft.ServiceFabric.Services.Runtime)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.runtime.statefulservice?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceFabric.Services.Runtime/StatefulService.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceFabric.Services.Runtime/StatefulService.xml)
* Service: **service-fabric**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Looking at the linked content, I'm seeing a link rendered in the current version across common browsers.  I'm going to close this out as resolved; please feel free to reopen if you believe this requires more discussion.
