### ISSUE TITLE
Incorrect link to azure storage product doc

### ISSUE THREAD

**Issue by tbolon** [Azure/azure-docs-sdk-dotnet#742]
The first link in the article (Azure Storage) points to <https://review.docs.microsoft.com/azure/storage/storage-introduction> which is an internal url.

The url should be <https://docs.microsoft.com/azure/storage/storage-introduction>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910dab69-65c9-d3b9-4bde-a04320ab8f7d
* Version Independent ID: d85d233b-9b65-e24a-390f-1dc1e5844b40
* Content: [Azure .NET Storage APIs](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet#feedback)
* Content Source: [api/overview/azure/storage.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.md)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Nice find! We'll fix it ASAP. 

Thanks!
