### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by minuz** [Azure/azure-docs-sdk-dotnet#749]
Hi, this article seems to be outdated. Was trying to follow a ms guid (https://docs.microsoft.com/en-us/azure/visual-studio/vs-storage-aspnet-getting-started-blobs#list-the-blobs-in-a-blob-container) but it seems like the `container.ListBlob()`  no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58f08265-bc3b-7f84-eac2-96eafb919566
* Version Independent ID: 1a0c5473-8d81-f363-f3b7-6cb37343a680
* Content: [CloudBlobContainer Class (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobcontainer?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobContainer.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobContainer.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
Were you trying in a .NET Core project, or a .NET Framework project? There are occasionally some extension methods that aren't carried over between the two.

**Comment by jsquire** [comment]
I'm going to close this out as the referenced article has ben updated to reflect v11 of the Storage library;  I'm not seeing any references to `ListBlob` in the content or code samples.  Please feel free to reopen if you believe this needs further discussion.
