### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by kiljoy001** [Azure/azure-docs-sdk-dotnet#752]
There is a misspelling in the properties section for the subsection 'Count' the word number is misspelt as "nunmber".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2fff563-62cd-3cd1-19ca-5bb0cabe00d9
* Version Independent ID: 88743eee-f292-12d0-03d7-b6a99f856953
* Content: [TokenCache Class (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.tokencache?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing this out as the spelling error appears to have been corrected;  please feel free to reopen if you believe further discussion is needed.
