### ISSUE TITLE
When is this property updated?

### ISSUE THREAD

**Issue by sujaysarma** [Azure/azure-docs-sdk-dotnet#758]
It would be useful to document all the codepaths that can result in LastModified being updated to reflect the actual timestamp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aea1ffe-04bc-639d-af09-c06f3a3f6b17
* Version Independent ID: 6f68416b-76b2-2364-dfbf-a72d56de1752
* Content: [FileProperties.LastModified Property (Microsoft.WindowsAzure.Storage.File)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.file.fileproperties.lastmodified?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.File/FileProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.File/FileProperties.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by sujayvsarma** [comment]
Ping!

**Comment by jsquire** [comment]
Closing this out as the referenced content no longer exists.  Please feel free to reopen if you feel further discussion is needed.
