### ISSUE TITLE
No overload for method UploadFromFileAsync(string) that takes 1 argument

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-docs-sdk-dotnet#759]
According to Visual Studio (15.8.1) the overload `UploadFromFileAsync(String)` doesn't exist.

To me this means that I can't give the method just one argument (as per docs) and I am assuming someone has updated one thing, but not the other.

I am referencing Microsoft.WindowsAzure.Storage version 4.3.0.0

It's highly likely that it is me doing something wrong, but I'd be interested to know what that is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd579abe-7784-403e-cd9e-a71a2394a742
* Version Independent ID: eb444a4c-7255-d3e0-64e4-ad2180980d6a
* Content: [CloudBlockBlob.UploadFromFileAsync Method (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblockblob.uploadfromfileasync?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Blob_CloudBlockBlob_UploadFromFileAsync_System_String_System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlockBlob.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlockBlob.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@arcotek-ltd .NET Core or Framework? IIRC correctly they expose slightly different overloads due to certain extension methods only being available in Framework, but I could be wrong.

@tamram can you comment?

**Comment by arcotek-ltd** [comment]
@camsoper,
Thanks for your reply. I'm using the framework.

I did get it to work, however, I had to add a combination of overloads.

Thanks

**Comment by tamram** [comment]
@arcotek-ltd - In earlier versions of the client library, that method required a System.IO.FileMode parameter. That parameter was removed back in version 7.0.0 (see [changelog](https://github.com/Azure/azure-storage-net/blob/master/changelog.txt#L182)).

The online reference documentation only reflects the latest version of the client library (which we recognize can be problematic when you're using an older version).
