### ISSUE TITLE
Please clarify what AssertionTypes would be valid here, or provide links to other documentation. 

### ISSUE THREAD

**Issue by seannybgoode** [Azure/azure-docs-sdk-dotnet#760]
The documentation here is incredibly sparse. Would really appreciate some elaboration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda09a3d-ffad-2ce0-5723-3d3659015d5c
* Version Independent ID: b995f2b5-4994-9984-8625-ad20def2b269
* Content: [UserAssertion.AssertionType Property (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.userassertion.assertiontype?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_UserAssertion_AssertionType)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/UserAssertion.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/UserAssertion.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing this out; I've transferred to the product repository.   Please see [#1719](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1719)
