### ISSUE TITLE
Import multipart form-data

### ISSUE THREAD

**Issue by abbgrade** [Azure/azure-docs-sdk-dotnet#772]
In the use with ImportsExtensions.PostImport method it's not clear what to give as FilePath, FileUrl to import without a temporary blob storage or OneDrive for business. Regarding to https://docs.microsoft.com/en-us/rest/api/power-bi/imports/postimport that should be possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8a0ef59-70bc-f2aa-6bf3-b865057407ae
* Version Independent ID: 07b0579b-2047-9f3a-c110-32ef725b06dd
* Content: [ImportInfo Class (Microsoft.PowerBI.Api.V2.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.v2.models.importinfo?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.PowerBI.Api.V2.Models/ImportInfo.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.PowerBI.Api.V2.Models/ImportInfo.xml)
* Service: **powerbi**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
I've spoken to the Power BI team and this has been moved to the internal repository that they use for tracking work.  They do have plans to address the request, though there is no timeline to share.

Given the age of the issue and that the API version is references is no longer the current version, I'm going to close this issue.   Please feel free to reopen if you believe that further discussion is needed.
