### ISSUE TITLE
what can the filter string do?

### ISSUE THREAD

**Issue by BenGood** [Azure/azure-docs-sdk-dotnet#773]
Could we have a link to something that explains how to build filters that this Where clause can consume? Based on this page I have no idea where to start. 

Are there other overloads for this method? I found some examples on stack exchange doing things like TableQuery&lt;CustomerEntity&gt;()
           .Where(TableQuery.GenerateFilterCondition("PartitionKey",
               QueryComparisons.Equal, "Harp"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67cf5814-8086-3ec6-703a-f054c4b937ad
* Version Independent ID: 1d7d514e-4079-9971-76bd-d2800480bc67
* Content: [TableQuery.Where(String) Method (Microsoft.WindowsAzure.Storage.Table)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.tablequery.where?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Table/TableQuery.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Table/TableQuery.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
@tamram Would you know?

**Comment by tamram** [comment]
@BenGood  @CamSoper - This page provides information on how to build filter strings: https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities.

You can also use LINQ to query: https://docs.microsoft.com/en-us/rest/api/storageservices/writing-linq-queries-against-the-table-service

**Comment by alexramsey92** [comment]
Please correct me if I am wrong but, "...[By] default, all entities in the table are returned if no filter expression is specified" is misleading as there is a query return limit of 1,000?

I agree with Ben, more detail here would be very helpful.

**Comment by jsquire** [comment]
Closing this out as the referenced content page no longer exists.  Please feel free to reopen if you believe this needs further discussion.
