### ISSUE TITLE
No summaries

### ISSUE THREAD

**Issue by breyed** [Azure/azure-docs-sdk-dotnet#774]
The pages for types and members in `Microsoft.ApplicationInsights` do not have summaries. Besides being bad when using the web, it's also a problem when using Visual Studio, since Visual Studio loses some information.

For example, Visual Studio generates the following C# for `EventTelemetry.Metrics` when you press F12:

``` c#
//
// Summary:
//     Gets a dictionary of application-defined event metrics. Learn more
public IDictionary<string, double> Metrics { get; }
```

The hyperlink for "Learn more" is lost. Normally, a workaround would be to press F1. The webpage for `Metrics` comes up, but since it doesn't have a summary, there's no way to learn more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d978f724-2b8b-ae68-d4ac-42553fdd46bc
* Version Independent ID: f2fed6b2-61ca-ec8b-aa06-1871bbcf8a75
* Content: [Client](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/insights/client?view=azure-dotnet)
* Content Source: [api/overview/azure/Insights/Client.yml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/live/api/overview/azure/Insights/Client.yml)
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing this out as the referenced content no longer exists.  Please feel free to reopen if you believe that further discussion is needed.
