### ISSUE TITLE
Possible values of ImportState

### ISSUE THREAD

**Issue by abbgrade** [Azure/azure-docs-sdk-dotnet#775]
What are the possible values of ImportState?
From https://docs.microsoft.com/en-us/rest/api/power-bi/imports/getimportbyid i know, that 'Publishing' and 'Succeeded' exist. What else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f0fd1c-3ea2-9a52-3bcc-d77c9b021bb5
* Version Independent ID: 90dd85d6-bc9d-a1d9-f858-a920ca723f49
* Content: [Import.ImportState Property (Microsoft.PowerBI.Api.V2.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.v2.models.import.importstate?view=azure-dotnet#Microsoft_PowerBI_Api_V2_Models_Import_ImportState)
* Content Source: [xml/Microsoft.PowerBI.Api.V2.Models/Import.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.PowerBI.Api.V2.Models/Import.xml)
* Service: **powerbi**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
I've spoken to the Power BI team and this has been moved to the internal repository that they use for tracking work.  They do have plans to address the request, though there is no timeline to share.

Given the age of the issue and that the API version is references is no longer the current version, I'm going to close this issue.   Please feel free to reopen if you believe that further discussion is needed.
