### ISSUE TITLE
Add a remark with link to how to configure IoT Hub for file load

### ISSUE THREAD

**Issue by wickste** [Azure/azure-docs-sdk-dotnet#777]
For this API reference topic it would be useful to have a remark that puts developers on the right path to configure their IoTHub for file upload, before calling this API:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-configure-file-upload

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e943e710-21dc-c256-c57c-8d2291118d06
* Version Independent ID: 24b0be74-e120-b361-30e5-28afa6a9a5d7
* Content: [DeviceClient.UploadToBlobAsync(String, Stream) Method (Microsoft.Azure.Devices.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient.uploadtoblobasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Client/DeviceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/DeviceClient.xml)
* Service: **iot-hub**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing as the API in the referenced content has been deprecated.

**Comment by wickste** [comment]
> Closing as the API in the referenced content has been deprecated.

@jsquire Why do you think this API has been deprecated?

**Comment by jsquire** [comment]
The referenced content marks it as such:

![image](https://user-images.githubusercontent.com/913445/108082646-5159f580-7040-11eb-8df6-528d886161ba.png)

**Comment by wickste** [comment]
Got it, my bad - I see the GetFileUploadSasURI API reference has the link now to configure the Hub for file upload.

**Comment by jsquire** [comment]
Thanks for the sanity check;  we've been asked to triage this repository and either transfer to the Azure SDK repo or close out stale issues.   Especially with some of the older issues, feedback from the domain experts is very helpful and appreciated.
