### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by taylorc** [Azure/azure-docs-sdk-dotnet#781]
"Gets or sets the content tpye descriptor." should be "Gets or sets the content type descriptor.". This spelling mistake is also shown in Intellisense in VS 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0581e7-68ff-0c80-06b3-7a23c7a9b951
* Version Independent ID: 2967ab14-a187-8880-337d-611715eeca79
* Content: [Message.ContentType Property (Microsoft.Azure.ServiceBus)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.message.contenttype?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus/Message.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/Message.xml)
* Service: **service-bus**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing; though the referenced content seems to be blank, the [source](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Message.cs#L249) shows the correction has been made.
