### ISSUE TITLE
Specify Limitations for Azure AD B2C V2

### ISSUE THREAD

**Issue by cvbc2010** [Azure/azure-docs-sdk-dotnet#788]
Currently Client Credentials and OBO flow is not working with these methods...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f297423f-ba8b-c7df-cd2c-c9e72032e55a
* Version Independent ID: 68eb5515-5682-4c5b-326b-8f479d4801c1
* Content: [ConfidentialClientApplication.AcquireTokenOnBehalfOfAsync Method (Microsoft.Identity.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplication.acquiretokenonbehalfofasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Client/ConfidentialClientApplication.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/ConfidentialClientApplication.xml)
* Service: **active-directory**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Closing, as the referenced content is no longer available.  (page 404)
