### ISSUE TITLE
Class is broken

### ISSUE THREAD

**Issue by singh722** [Azure/azure-docs-sdk-dotnet#790]
This Class is broken. The StorageAccountCreateParameters in Microsoft.Azure.Management.Storage.Models and the Microsoft.WindowsAzure.Management.Storage.Models have same properties and methods. So basically the class never got updated. The StorageAccountCreateParameters in Microsoft.Azure.Management.Storage.Models is supposed to be supporting more properties like Kind and AccessTier. I do not see any of these in Visual Studio 2017. It's the old class from Microsoft.WindowsAzure.Management.Storage.Models namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51407ad7-47ab-24f8-c720-ee98ed79bc19
* Version Independent ID: 48af1385-09e1-e50e-d8cb-032dddc27210
* Content: [StorageAccountCreateParameters Class (Microsoft.Azure.Management.Storage.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.storageaccountcreateparameters?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Storage.Models/StorageAccountCreateParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Storage.Models/StorageAccountCreateParameters.xml)
* Service: **storage**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by babin93** [comment]
I also experience this issue. The doc states properties that do not exist, when I try to use the class.

**Comment by jsquire** [comment]
Closing; this appears to be corrected.   I'm seeing the `Kind` and `AccessTier` mentioned and do not see discrepancies against the source at a glance.
