### ISSUE TITLE
Singleton or per request

### ISSUE THREAD

**Issue by santo2** [Azure/azure-docs-sdk-dotnet#803]
Can you create this service proxy once at startup, or should you create this again per request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a528a1d-5cc8-5323-19d0-6fc9f314c888
* Version Independent ID: 5bf1c68a-35c9-deda-bfaf-2acb9e157152
* Content: [ServiceProxy.Create(Uri, ServicePartitionKey, TargetReplicaSelector, String) Method (Microsoft.ServiceFabric.Services.Remoting.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.remoting.client.serviceproxy.create?view=azure-dotnet#Microsoft_ServiceFabric_Services_Remoting_Client_ServiceProxy_Create__1_System_Uri_Microsoft_ServiceFabric_Services_Client_ServicePartitionKey_Microsoft_ServiceFabric_Services_Communication_Client_TargetReplicaSelector_System_String_)
* Content Source: [xml/Microsoft.ServiceFabric.Services.Remoting.Client/ServiceProxy.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceFabric.Services.Remoting.Client/ServiceProxy.xml)
* Service: **service-fabric**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by CamSoper** [comment]
A singleton should be fine.
