### ISSUE TITLE
Can we use an existing Service Plan ?

### ISSUE THREAD

**Issue by krebipeti** [Azure/azure-docs-sdk-dotnet#828]
IWebApp app1 = azure.WebApps
    .Define("MyUniqueWebAddress")
    .WithRegion(Region.USWest)
    .WithNewResourceGroup("MyResourceGroup")
    .WithNewWindowsPlan(PricingTier.StandardS1)
    .Create();

from this code, i have tried my self, we only able to use existing resource group. unfortunately there is no method to use existing service plan i can find. is there any workaround available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277adb93-5a3c-b8bb-44bd-22c55722d92d
* Version Independent ID: e1c13879-63dd-2e01-2759-a8ac7a49670a
* Content: [Azure App Service libraries for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/appservice?view=azure-dotnet)
* Content Source: [api/overview/azure/appservice.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/appservice.md)
* Service: **app-service**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@krebipeti You need to use `.WithExistingWindowsPlan` or `.WithExistingLinuxPlan` which are both extensions available immediately after `.Define()`.
