### ISSUE TITLE
CloudStorageAccount - wrong commentaries

### ISSUE THREAD

**Issue by DarioSulser** [Azure/azure-docs-sdk-dotnet#836]
Line 7 is Code, that should be combined with Line9 (and NOT set as comment)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 0eead831-001f-122a-8fc5-311d82c65ada
* Version Independent ID: d01dffc0-5240-bbac-f30c-4373124ab7cf
* Content: [CloudStorageAccount.CreateCloudBlobClient Method (Microsoft.WindowsAzure.Storage)](https://docs.microsoft.com/de-ch/dotnet/api/microsoft.windowsazure.storage.cloudstorageaccount.createcloudblobclient?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.WindowsAzure.Storage/CloudStorageAccount.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage/CloudStorageAccount.xml)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Closing; the referenced content does not exist.  (page 404)
