### ISSUE TITLE
Transport type

### ISSUE THREAD

**Issue by alexsniffin** [Azure/azure-docs-sdk-dotnet#844]
For `EventProcessorHost(String, String, String, String, String)` when passing in the connection string, you can append other constructor options such as `;TransportType=1`, this will fix issues for specific users with network problems when using amqp. This is a obscure in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f983281-5a7d-7aba-0fb3-18e176d8dc01
* Version Independent ID: a4c85f01-3a40-467a-2456-7915a333d5d4
* Content: [EventProcessorHost Class (Microsoft.Azure.EventHubs.Processor)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.eventprocessorhost?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventHubs.Processor/EventProcessorHost.xml)
* Service: **event-hubs**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by amir734jj** [comment]
**Work around**: `TransportType` is a property in the connection string, we can modify an exisiting connection string and safely set the `TransportType`:

```csharp
new EventHubsConnectionStringBuilder("event-hub-connection-string")
{
    TransportType = TransportType.AmqpWebSockets
}.ToString()
```

**Comment by CamSoper** [comment]
@alexsniffin and @amir734jj  - Thanks for your feedback.  Pending expanding the doc, I'll leave this issue open so other readers will see it.

**Comment by spelluru** [comment]
#please-close

**Comment by spelluru** [comment]
#assign:spelluru

**Comment by jsquire** [comment]
Closing per request from @spelluru
