### ISSUE TITLE
CloudStorageAccount Parse Needs Additional Information Connection String

### ISSUE THREAD

**Issue by laultman** [Azure/azure-docs-sdk-dotnet#845]
You do not give any example or a link to what a connection string looks like. So here is the link to full article: https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string
and here is the topic title link: https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-for-an-azure-storage-account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa925dbc-ba56-34f0-2a62-3f0fda384ad7
* Version Independent ID: 6f601300-48d0-5fe7-3a53-a781e0d81d0b
* Content: [CloudStorageAccount.Parse(String) Method (Microsoft.WindowsAzure.Storage)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.cloudstorageaccount.parse?view=azure-dotnet)
* Content Source: [xml/Microsoft.WindowsAzure.Storage/CloudStorageAccount.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage/CloudStorageAccount.xml)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Closing; the referenced content does not exist.  (page 404)
