### ISSUE TITLE
Performance Levels are now retired

### ISSUE THREAD

**Issue by alohaninja** [Azure/azure-docs-sdk-dotnet#853]
Is this property being deprecated now that [performance levels are no longer used](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-levels)?

Is the preferred way of assigning scale to use `OfferThroughput` now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba86803-405b-8aac-88cd-887fadb36391
* Version Independent ID: c57a141f-9b9f-a9e7-8947-ecdee47bd151
* Content: [RequestOptions.OfferType Property (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.offertype?view=azure-dotnet#Microsoft_Azure_Documents_Client_RequestOptions_OfferType)
* Content Source: [xml/Microsoft.Azure.Documents.Client/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by SnehaGunda** [comment]
@alohaninja apologies for the really long delay on this, somehow I missed the notification. RequestOptions.OfferThroughput property is used to set the throughput, you can see the syntax and examples in the following doc: 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.offerthroughput?view=azure-dotnet

**Comment by SnehaGunda** [comment]
@CamSoper please close this issue if there aren't any further questions.
