### ISSUE TITLE
Microsoft Azure Mobile Client API explorer contains both server and client

### ISSUE THREAD

**Issue by RobDesideri** [Azure/azure-docs-sdk-dotnet#857]
This section should only explore `Client` API.

Instead, at the moment, the section mixes `Server` and `Client` APIs, making it very difficult to find the client references (also because these are linked to the old `MobileService` namespace, so there is no trace of the `Client` word).

A properly `Client` section should contains the `Microsoft.Azure.Mobile.Client` package namespaces, i.e.

- Microsoft.WindowsAzure.MobileServices
- Microsoft.WindowsAzure.MobileServices.Eventing
- Microsoft.WindowsAzure.MobileServices.Query
- Microsoft.WindowsAzure.MobileServices.Sync
- Microsoft.WindowsAzure.MobileServices.Threading

([Nuget reference](https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/)).

Instead `Server` section should contains all related `Server`s namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147e67ac-ad9e-4818-3a9d-877bbb7f3877
* Version Independent ID: 0c691397-82f5-2d98-ea22-8a33407d3c7b
* Content: [Client](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/mobileapps/client?view=azure-dotnet)
* Content Source: [api/overview/azure/MobileApps/Client.yml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/live/api/overview/azure/MobileApps/Client.yml)
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Actually, I just realized what happened.  It's called the "client API" on this page because it's an Azure service client API (we call them data-plane APIs), as opposed to a *management* API.  So it's consistent with all our other service landing pages, even if the combination of a client for a server service is confusing.
