### ISSUE TITLE
Microsoft Azure Mobile Client refers to Server library

### ISSUE THREAD

**Issue by RobDesideri** [Azure/azure-docs-sdk-dotnet#858]
This page declares to refer to the **client** library but instead points to the **server** library.

So, if you install the declared nuget package (`Microsoft.Azure.Mobile.Server`) you install the server package, not the client (`Microsoft.Azure.Mobile.Client`) package.

And, if you click on the "Explore the _client_ APIs" button, you are redirect into an API explorer that mix server and client APIs (see #857).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693ffbf0-e505-020e-f7d2-e75932eb22fd
* Version Independent ID: aa2d9e02-95a2-a99d-0a3f-461e1cea040a
* Content: [Azure Mobile libraries for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/mobile?view=azure-dotnet)
* Content Source: [api/overview/azure/mobile.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/mobile.md)
* Service: **app-service**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Same deal with this one.  I totally get what you're saying, and I might revisit it in the future, but for the moment it's consistent with our terminology.
