### ISSUE TITLE
Strange sentence

### ISSUE THREAD

**Issue by buzzfrog** [Azure/azure-docs-sdk-dotnet#860]
"Gets the maximum size of a documents within a collection"
What does it mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da7f9c4f-8e99-1d81-f9f1-8f3e1bf81b52
* Version Independent ID: 2a196d2a-9ff4-7cee-6589-91000d80bc23
* Content: [ResourceResponseBase.DocumentQuota Property (Microsoft.Azure.Documents.Client)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.resourceresponsebase.documentquota?view=azure-dotnet#Microsoft_Azure_Documents_Client_ResourceResponseBase_DocumentQuota)
* Content Source: [xml/Microsoft.Azure.Documents.Client/ResourceResponseBase.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/ResourceResponseBase.xml)
* Service: **cosmos-db**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@SnehaGunda ?

**Comment by SnehaGunda** [comment]
@buzzfrog apologies for the really long delay somehow I missed the notification. Azure Cosmos DB expects an item/document size to be 2 MB or less for optimal performance and cost benefits. and this method returns the maximum size of an item in a collection. These docs are autogenerated from the source SDK,  I send an email to the dev team to update the description to the following, and add more context if possible:

_Gets the maximum size of an item in a collection. The size is returned by this property is represented in kilobytes._

**Comment by jsquire** [comment]
Closing; the requested clarification was added.
