### ISSUE TITLE
BlobWriterOverwriteFiles and BlobWriterAddHeader not working

### ISSUE THREAD

**Issue by juanidambrosio** [Azure/azure-docs-sdk-dotnet#862]
I set BlobWriterOverwriteFiles to false and BlobWriterAddHeader to true, but when writing to a Sink Blob it actually overwrites my previous content and doesn't put a header in my JSON. Do these properties have another purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66749aa2-4560-d5f9-afc6-a8d47da42a47
* Version Independent ID: b1510a79-e5d9-281c-5737-e15fd6fb08f0
* Content: [BlobSink.BlobWriterOverwriteFiles Property (Microsoft.Azure.Management.DataFactories.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactories.models.blobsink.blobwriteroverwritefiles?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.DataFactories.Models/BlobSink.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.DataFactories.Models/BlobSink.xml)
* Service: **data-factory**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@tamram ?

**Comment by tamram** [comment]
@CamSoper - This is actually an Azure Data Factory API, not Azure Storage.

@linda33wj @douglaslMS - Can one of you help get this to the right person? Thanks!

**Comment by CamSoper** [comment]
@tamram - Oh my, you're right!  I didn't even look at the namespace, just the property name.  How embarassing!  😆 

Thanks!

**Comment by tamram** [comment]
@CamSoper - no problem!

**Comment by douglaslMS** [comment]
@juanidambrosio A Data Factory developer has reviewed the code for both the Azure portal and the Data Factory backend, and Data Factory does not currently set there properties. In other words, these properties are not currently in use. It seems that they are not yet implemented, and therefore that you cannot actually use them.

**Comment by CamSoper** [comment]
@douglaslMS That would be me!  Sorry, I tend to only tune into the conversations I'm not directly involved in when I'm reviewing open issues or when someone @ s me.
