### ISSUE TITLE
How long it takes before this property turns to true as a result of REST API call post replication is configured in another region.

### ISSUE THREAD

**Issue by badalk** [Azure/azure-docs-sdk-dotnet#863]
I have a Database replication to another region and the deployment is completed but my REST API call to get database information for the primary database is still showing zoneRedundant as false despite of waiting for 10 mins. So does it take some time to reflect the updated property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea92d105-9a9d-bfc2-747a-285067a363d6
* Version Independent ID: dccb0d89-a05b-eb5a-fdfc-b0c4bf1d462d
* Content: [Database.ZoneRedundant Property (Microsoft.Azure.Management.Sql.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sql.models.database.zoneredundant?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Sql.Models/Database.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Sql.Models/Database.xml)
* Service: **sql-database**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
@CarlRabeler ?

**Comment by CarlRabeler** [comment]
@anosov1960 Sasha - do you know the answer to this? I do not. My guess would be yes, but it is just an educated guess.

**Comment by badalk** [comment]
Despite of waiting for 12 hours the REST API response does not show zoneRundandnt attribute value as true even though the geo-replication is configured and active.

**Comment by CarlRabeler** [comment]
Adding Sasha

**Comment by anosov1960** [comment]
Zone Redundant database and geo-replication are two different and independent features. Zone Redundant is a HA configuration that distributes local sync database replicas across multiple availability zones in the same region. Geo-replication is a DR technology that creates a async secondary database in a different region. ZR is a feature of Premium or Business Critical service tier. Geo-replication is supported by all service tiers.

**Comment by CarlRabeler** [comment]
I replied on GitHub

From: Carl Rabeler <Carl.Rabeler@microsoft.com>
Sent: Friday, October 19, 2018 10:10 AM
To: Azure/azure-docs-sdk-dotnet <reply@reply.github.com>; Azure/azure-docs-sdk-dotnet <azure-docs-sdk-dotnet@noreply.github.com>; Sasha Nosov <sashan@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-docs-sdk-dotnet] How long it takes before this property turns to true as a result of REST API call post replication is configured in another region. (#863)

Adding Sasha

**Comment by CarlRabeler** [comment]
#please-close
