### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by wcabus** [Azure/azure-docs-sdk-dotnet#864]
To be more clear, this page could state that when the ContinuationToken is `null` or an empty string, there is no additional data available in the query. This information could also be added to methods that return a `CollectionQueryResult<T>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 774caef3-80a7-78c9-678b-58b82eea8c68
* Version Independent ID: 5575a0ad-f8a0-252d-d8e6-1e89c2ef763b
* Content: [CollectionQueryResult&lt;T&gt;.ContinuationToken Property (Microsoft.Azure.NotificationHubs)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.collectionqueryresult-1.continuationtoken?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/CollectionQueryResult`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/CollectionQueryResult`1.xml)
* Service: **notification-hubs**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jwargo** [comment]
@sethmanheim are you looking into this?

**Comment by sethmanheim** [comment]
@jwargo No, never saw this, probably because I'm not listed as the author.

**Comment by sethmanheim** [comment]
@jwargo I would think this change needs to be made in the code, within the triple-slash doc comments since it's probably autogenerated.
