### ISSUE TITLE
Bootstrapping ListBlobsSegmentedAsync's currentToken argument

### ISSUE THREAD

**Issue by chwarr** [Azure/azure-docs-sdk-dotnet#865]
All of the `CloudBlobDirectory.ListBlobsSegmentedAsync` overloads take a `BlobContinuationToken currentToken` argument. This is documented as "A continuation token returned by a previous listing operation.". Can this documentation be updated to address how to start listing when I don't yet have a continuation token? E.g., should I pass `null`? `new BlobContinuationToken()`? something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f08f1295-f58a-9237-d040-6aa635467773
* Version Independent ID: 32f84e5c-e782-7935-0d16-261c9de62849
* Content: [CloudBlobDirectory.ListBlobsSegmentedAsync Method (Microsoft.WindowsAzure.Storage.Blob)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobdirectory.listblobssegmentedasync?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Blob_CloudBlobDirectory_ListBlobsSegmentedAsync_Microsoft_WindowsAzure_Storage_Blob_BlobContinuationToken_)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobDirectory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobDirectory.xml)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by chwarr** [comment]
Looks like the answer to this is `null`.

I looked at [the implementation of `CloudBlobContainer.ListBlobs`](https://github.com/Azure/azure-storage-net/blob/8c426573fda5c0caa6704a2d0f9af0acef0e7b9f/Lib/ClassLibraryCommon/Blob/CloudBlobContainer.cs#L814-L830)--the version that gets all of the items. It uses an internal helper method, [`LazyEnumerable`](https://github.com/Azure/azure-storage-net/blob/8c426573fda5c0caa6704a2d0f9af0acef0e7b9f/Lib/Common/Core/Util/CommonUtility.cs#L351-L381) that seeds the continuation token with `null`.

**Comment by CamSoper** [comment]
@chwarr Thank you for coming back to post your findings!

**Comment by jsquire** [comment]
Closing; the referenced content does not exist.  (page 404)

**Comment by chwarr** [comment]
This issue still exists. I have updated the metadata to point to the now-current location. Please re-open.

**Comment by jsquire** [comment]
Thank you for your feedback, @chwarr.    Reopening and migrating to the Azure SDK repository so that this can be addressed.
