### ISSUE TITLE
it returns a task so there is no way to know whether it exists or not. 

### ISSUE THREAD

**Issue by rameshjanjyam** [Azure/azure-docs-sdk-dotnet#867]
This method is not returning any value that can identify whether it exists or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65059500-e2a4-0cec-9e49-8904cdf55eb1
* Version Independent ID: 4c01d647-25fb-b64a-593a-f4cceb0eb681
* Content: [RedisOperationsExtensions.CheckNameAvailabilityAsync(IRedisOperations, CheckNameAvailabilityParametersInner, CancellationToken) Method (Microsoft.Azure.Management.Redis.Fluent)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.redis.fluent.redisoperationsextensions.checknameavailabilityasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Redis.Fluent/RedisOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Redis.Fluent/RedisOperationsExtensions.xml)
* Service: **redis-cache**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by stylesm** [comment]
The method calls `Microsoft.Azure.Management.Fluent.CheckNameAvailabilityWithHttpMessagesAsync`, which in turn throws an Exception if the HTTP status code returned is not a 200 OK.

Typical pattern would be to wrap the call in a try-catch block and handle the exception thrown.

If the method were to return a value (a bool presumably), I imagine it would be called `IsNameAvailableAsync()`,
