### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-docs-sdk-dotnet#881]
Link to Migration Assistant (first link in Additional Reading) is broken, just re-directs to ACOM site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3372e8a4-e2e4-27a7-a6dd-57935b5aee79
* Version Independent ID: f3a45d80-93cd-ef26-2eb7-f4b9c68dc625
* Content: [Migrate your .NET web app or service to Azure App Service](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-howto-migrate-app-service?view=azure-dotnet)
* Content Source: [docs-ref-conceptual/dotnet-howto-migrate-app-service.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-howto-migrate-app-service.md)
* Service: **app-service**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by intrepidsoldier** [comment]
It should point to: https://migrate4.azurewebsites.net/

**Comment by glloyd2010f** [comment]
Would it actually be https://appmigration.microsoft.com/ (even though this is in preview) since they are deprecating that product?

**Comment by jsquire** [comment]
Closing; the broken link was addressed in the merged PR.
