### ISSUE TITLE
Can you run the app pool that Azure App Service uses as a domain user if your domain has federated with ADFS?

### ISSUE THREAD

**Issue by MarkIannucci** [Azure/azure-docs-sdk-dotnet#907]
I'm thinking the answer on this is no, if that is the case, it would be great if this document indicated that was one of the limitations of App Service as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3372e8a4-e2e4-27a7-a6dd-57935b5aee79
* Version Independent ID: f3a45d80-93cd-ef26-2eb7-f4b9c68dc625
* Content: [Migrate your .NET web app or service to Azure App Service - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-howto-migrate-app-service?view=azure-dotnet)
* Content Source: [docs-ref-conceptual/dotnet-howto-migrate-app-service.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-howto-migrate-app-service.md)
* Service: **app-service**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Correct, I'm 99% sure the answer is no. Is this a scenario you still need to support?
