### ISSUE TITLE
Azure Database Migration Service is no longer in Preview

### ISSUE THREAD

**Issue by HJToland3** [Azure/azure-docs-sdk-dotnet#918]
Can you update the following text under the FAQ heading, or let me know how I can update the page?

Under the question, "I want to go PaaS but I'm not sure if my database is compatible. Are there tools to help?"

Update the answer to read, "Yes. The Data Migration Assistant is a tool that is used as a part of migrating to Azure SQL Database. In addition, you can use the Azure Database Migration Service for either IaaS or PaaS migrations."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093422a4-7cdf-da1e-fb06-5e32dfa3bda9
* Version Independent ID: 1126e129-066f-2d75-fc4a-fc9f5db44476
* Content: [Migrate a SQL Server database to Azure - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-howto-migrate-sql?view=azure-dotnet)
* Content Source: [docs-ref-conceptual/dotnet-howto-migrate-sql.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-howto-migrate-sql.md)
* Service: **sql-database**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by CamSoper** [comment]
Doc no longer exists
