### ISSUE TITLE
How does one cross reference own api documentation with Azure SDK reference documentation? 

### ISSUE THREAD

**Issue by bloudraak** [Azure/azure-docs-sdk-dotnet#928]
We have written a metric ton of code with document comments and are looking at using docfx to generate documentation. Much of the code is written in C# uses the Azure SDK. When we use docfx to generate our documentation, references to Azure SDK is missing, while references to the BCL is resolved using the [Microsoft Docs cross reference services](https://xref.docs.microsoft.com). 

The [docfx documentation](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html#cross-reference-services) recommends that we upload an xrefmap.yml to our site, which can then be references from other documentation.  Has something like this been done for the Azure SDK so we can cross reference types exposed by the SDK?

For example, we'll have a parameter of type `IAzure`. Docfx can generate link the parameter to the appropriate reference documentation produced by this website. Currently its just empty.

**Comment by CamSoper** [comment]
Sorry for the late reply on this, I just saw it. I'm sorry to say, it's totally outside my area of expertise, though. I'd suggest https://github.com/dotnet/docfx
