### ISSUE TITLE
Microsoft.Azure.DocumentDB extension methods polluting all classes

### ISSUE THREAD

**Issue by bojunehsu** [Azure/azure-docs-sdk-dotnet#968]
3 extension methods defined in Microsoft.Azure.DocumentDB is polluting all classes as they are defined over Object instead of a specific class.

See https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.computervision.models.boundingrect?view=azure-dotnet for an example.

![image](https://user-images.githubusercontent.com/1988517/55968027-e013c380-5cad-11e9-9a0b-73f8b1a7cd97.png)

Here is the source of these extensions.
https://github.com/Azure/azure-docs-sdk-dotnet/blob/0ccda06c3b21ce36969496b6091c4cc710cac1c3/xml/Microsoft.Azure.Documents.SystemFunctions/TypeCheckFunctionsExtensions.xml

**Comment by jsquire** [comment]
Closing, as the extension methods no longer seem to be appearing in the documentation for other libraries (from a random sampling).    Please feel free to reopen if you believe that further discussion is needed.
